### ISSUE TITLE
[Bug] Crash on server version 1.20

### ISSUE THREAD

**Issue by JosiahGertz** [quiqueck/BCLib#108]
### What happened?

Tried running my 1.20 server with BetterEnd version 4.0.7 and got a crash report: The mod "wunderlib" contains invalid entries in its mod json: Unsupported root entry "modmenu" at line 26 column 12

This crash only happens when I have the BetterEnd mod installed.

These are the mods I have on the server:

AdditionalStructures-1.20.x-(v.4.2.0).jar
architectury-9.0.8-fabric.jar
bclib-3.0.10.jar
better-end-4.0.7.jar
biomemakeover-FABRIC-1.20.0-1.10.0.jar
fabric-api-0.83.0+1.20.jar
friendsandfoes-fabric-mc1.20-1.9.0.jar

### BCLib

3.0.10

### Fabric API

0.83.0

### Fabric Loader

0.14.21

### Minecraft

1.20.0

### Relevant log output

```shell
https://mclo.gs/X5AEoov

[14:30:43] [main/INFO]: Loading Minecraft 1.20 with Fabric Loader 0.14.21
[14:30:44] [ForkJoinPool-1-worker-1/WARN]: The mod "wunderlib" contains invalid entries in its mod json:
- Unsupported root entry "modmenu" at line 26 column 12
[14:30:44] [main/INFO]: Loading 50 mods:
	- additionalstructures 4.2.0
	- architectury 9.0.8
	- bclib 3.0.10
	   \-- wunderlib 1.1.3
	- betterend 4.0.7
	- biomemakeover 1.20.0-1.10.0
	   \-- taniwha 1.20.0-5.1.0
	- fabric-api 0.83.0+1.20
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-api-lookup-api-v1 1.6.34+4d8536c927
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b27
	   |-- fabric-block-api-v1 1.0.9+e022e5d127
	   |-- fabric-blockrenderlayer-v1 1.1.39+b3afc78b27
	   |-- fabric-client-tags-api-v1 1.0.20+b3afc78b27
	   |-- fabric-command-api-v1 1.2.32+f71b366f27
	   |-- fabric-command-api-v2 2.2.11+b3afc78b27
	   |-- fabric-commands-v0 0.2.49+df3654b327
	   |-- fabric-containers-v0 0.1.61+df3654b327
	   |-- fabric-content-registries-v0 4.0.7+b3afc78b27
	   |-- fabric-convention-tags-v1 1.5.3+b3afc78b27
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe27
	   |-- fabric-data-generation-api-v1 12.1.10+b3afc78b27
	   |-- fabric-dimensions-v1 2.1.51+b3afc78b27
	   |-- fabric-entity-events-v1 1.5.21+b3afc78b27
	   |-- fabric-events-interaction-v0 0.6.0+b3afc78b27
	   |-- fabric-events-lifecycle-v0 0.2.61+df3654b327
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a27
	   |-- fabric-item-api-v1 2.1.26+b3afc78b27
	   |-- fabric-item-group-api-v1 4.0.7+b3afc78b27
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da27
	   |-- fabric-keybindings-v0 0.2.34+df3654b327
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   |-- fabric-loot-api-v2 1.1.37+b3afc78b27
	   |-- fabric-loot-tables-v1 1.1.41+9e7660c627
	   |-- fabric-message-api-v1 5.1.6+b3afc78b27
	   |-- fabric-mining-level-api-v1 2.1.47+b3afc78b27
	   |-- fabric-models-v0 0.3.35+b3afc78b27
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b27
	   |-- fabric-networking-v0 0.3.48+df3654b327
	   |-- fabric-object-builder-api-v1 11.0.6+b3afc78b27
	   |-- fabric-particles-v1 1.0.28+b3afc78b27
	   |-- fabric-recipe-api-v1 1.0.18+b3afc78b27
	   |-- fabric-registry-sync-v0 2.2.6+b3afc78b27
	   |-- fabric-renderer-api-v1 3.0.1+b3afc78b27
	   |-- fabric-renderer-indigo 1.3.1+b3afc78b27
	   |-- fabric-renderer-registries-v1 3.2.44+df3654b327
	   |-- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b27
	   |-- fabric-rendering-fluids-v1 3.0.26+b3afc78b27
	   |-- fabric-rendering-v0 1.1.47+df3654b327
	   |-- fabric-rendering-v1 3.0.6+b3afc78b27
	   |-- fabric-resource-conditions-api-v1 2.3.4+b3afc78b27
	   |-- fabric-resource-loader-v0 0.11.7+f7923f6d27
	   |-- fabric-screen-api-v1 2.0.6+b3afc78b27
	   |-- fabric-screen-handler-api-v1 1.3.27+b3afc78b27
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b27
	   |-- fabric-transfer-api-v1 3.2.2+b3afc78b27
	   \-- fabric-transitive-access-wideners-v1 4.2.0+b3afc78b27
	- fabricloader 0.14.21
	- friendsandfoes 1.9.0
	   \-- com_github_llamalad7_mixinextras 0.1.1
	- java 17
	- minecraft 1.20
[14:30:44] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/server/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[14:30:44] [main/INFO]: Compatibility level set to JAVA_16
[14:30:44] [main/INFO]: Compatibility level set to JAVA_17
[14:30:59] [main/INFO]: [bclib] Added Config bclib.generator to auto sync (file hash)
[14:30:59] [main/INFO]: [bclib] Added Config bclib.main to auto sync (content diff)
[14:30:59] [main/INFO]: [bclib] Added Config bclib.biomes to auto sync (file hash)
[14:30:59] [main/INFO]: [bclib] Added Config betterend.entities to auto sync (file hash)
[14:30:59] [main/INFO]: [bclib] Added Config betterend.blocks to auto sync (file hash)
[14:30:59] [main/INFO]: [bclib] Added Config betterend.items to auto sync (file hash)
[14:30:59] [main/INFO]: [bclib] Added Config betterend.biomes to auto sync (file hash)
[14:30:59] [main/INFO]: [bclib] Added Config betterend.recipes to auto sync (file hash)
[14:30:59] [main/INFO]: [bclib] Added Config betterend.enchantments to auto sync (file hash)
[14:31:17] [main/INFO]: Registering C2S receiver with id biomemakeover:cl_complete_quest
[14:31:17] [main/INFO]: Registering C2S receiver with id biomemakeover:update_dir_data
[14:31:17] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:31:18] [main/INFO]: [bclib] Running Pre Patchers on ./world/.
[14:31:18] [main/INFO]: [DataFixerAPI] Everything up to date
[14:31:18] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Some intrusive holders were not registered: [Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}]
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:209) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
Caused by: java.lang.IllegalStateException: Some intrusive holders were not registered: [Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}, Reference{null=air}]
	at net.minecraft.class_2370.method_40276(class_2370.java:364) ~[server-intermediary.jar:?]
	at net.minecraft.class_5455$class_6892.method_40332(class_5455.java:41) ~[server-intermediary.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at net.minecraft.class_5455$class_6891.<init>(class_5455.java:64) ~[server-intermediary.jar:?]
	at net.minecraft.class_5455$class_7781.<init>(class_5455.java:105) ~[server-intermediary.jar:?]
	at net.minecraft.class_5455.method_40316(class_5455.java:109) ~[server-intermediary.jar:?]
	at net.minecraft.class_7780.<init>(class_7780.java:36) ~[server-intermediary.jar:?]
	at net.minecraft.class_7780.method_45929(class_7780.java:88) ~[server-intermediary.jar:?]
	at net.minecraft.class_7780.method_45930(class_7780.java:67) ~[server-intermediary.jar:?]
	at net.minecraft.class_7659.method_45139(class_7659.java:21) ~[server-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:31) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_43612(Main.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:944) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	... 4 more
```

### Other Mods

```shell
AdditionalStructures-1.20.x-(v.4.2.0).jar
architectury-9.0.8-fabric.jar
better-end-4.0.7.jar
biomemakeover-FABRIC-1.20.0-1.10.0.jar
fabric-api-0.83.0+1.20.jar
friendsandfoes-fabric-mc1.20-1.9.0.jar
```

**Comment by CamperSamu** [comment]
Try generating a world from the client, then quit right after you join and copy it over to your server.
Might help for now

**Comment by quiqueck** [comment]
Tried to reproduce this issue with the following mod version:
- additionalstructures 4.2.0
- architectury 9.0.8
- badpackets 0.4.1
- bclib 3.0.11
- betterend 4.0.7
- biomemakeover 1.20.0-1.10.1
- cardinal-components-base 5.2.1
- emi 1.0.3+1.20+fabric
- fabric-api 0.83.1+1.20.1
- fabricloader 0.14.21
- friendsandfoes 1.9.2
- minecraft 1.20.1
- trinkets 3.7.0
- wthit 8.1.0
- wunderlib 1.1.3

Unfortunately, the crash did not happen. Maybe the updated I already prepared, or the updates from the other mods fixed the issue... Could you maybe try with the latest Version of the other mods as well?
