### ISSUE TITLE
[Bug - 1.20.x] BCLib fails to create the biome list when using datapacks 2: Electric Boogaloo 

### ISSUE THREAD

**Issue by CamperSamu** [quiqueck/BCLib#110]
### What happened?

While the last issue (#105) is fixed and Stellarity now works, issues still persist with the Terralith datapack (not with the mod tho, but because of Traverse I need to use the datapack version).
Something with Terralith causes a StackOverflowException during or directly after the biome list creation.

### BCLib

3.0.10

### Fabric API

0.84.0+1.20.1

### Fabric Loader

0.14.21

### Minecraft

1.20.1

### Relevant log output

```shell
[20:52:27] [Server thread/INFO] (Minecraft) Starting integrated minecraft server version 1.20.1
[20:52:27] [Server thread/INFO] (Minecraft) Generating keypair
[20:52:27] [Server thread/INFO] (Logger) [bclib] 
Apply Modifications for minecraft:the_nether
    BCLib - Nether BiomeSource (a855e48)
        biomes     = 36
        namespaces = minecraft(5), betternether(22), cinderscapes(4), regions_unexplored(5)
        seed       = 0
        height     = 256
        config     = BCLibNetherBiomeSourceConfig{mapVersion=hex, useVerticalBiomes=true, amplified=true, biomeSize=256, biomeSizeVertical=80}
[20:52:27] [Server thread/INFO] (Logger) [bclib] 
Apply Modifications for minecraft:overworld
    class_4766 (6a7c02f8)
        biomes     = 241
        namespaces = terralith(94), regions_unexplored(65), minecraft(53), terrestria(18), profundis(4), traverse(7)
[20:52:27] [Server thread/INFO] (Logger) [bclib] 
Apply Modifications for minecraft:the_end
    BCLib - The End  BiomeSource (36b0fe6b)
        biomes     = 39
        namespaces = betterend(19), far_end(8), stellarity(7), minecraft(5)
        seed       = 0
        height     = 256
        deciders   = 1
        config     = BCLEndBiomeSourceConfig{mapVersion=hex, generatorVersion=paulevs, withVoidBiomes=true, innerVoidRadiusSquared=1048576, voidBiomesSize=256, centerBiomesSize=256, landBiomesSize=256, barrensBiomesSize=256}
[20:52:27] [Server thread/INFO] (Logger) [bclib] World Dimensions: 
 - minecraft:the_nether: 
     BCLib - Chunk Generator (21f32010) 
     BCLib - Nether BiomeSource (a855e48)
         biomes     = 36
         namespaces = minecraft(5), betternether(22), cinderscapes(4), regions_unexplored(5)
         seed       = 0
         height     = 256
         config     = BCLibNetherBiomeSourceConfig{mapVersion=hex, useVerticalBiomes=true, amplified=true, biomeSize=256, biomeSizeVertical=80}
 - minecraft:overworld: 
     net.minecraft.class_3754@3283c96b 
     class_4766 (6a7c02f8)
         biomes     = 241
         namespaces = terralith(94), regions_unexplored(65), minecraft(53), terrestria(18), profundis(4), traverse(7)
 - minecraft:the_end: 
     BCLib - Chunk Generator (203ac39) 
     BCLib - The End  BiomeSource (36b0fe6b)
         biomes     = 39
         namespaces = betterend(19), far_end(8), stellarity(7), minecraft(5)
         seed       = 0
         height     = 256
         deciders   = 1
         config     = BCLEndBiomeSourceConfig{mapVersion=hex, generatorVersion=paulevs, withVoidBiomes=true, innerVoidRadiusSquared=1048576, voidBiomesSize=256, centerBiomesSize=256, landBiomesSize=256, barrensBiomesSize=256}
[20:52:27] [Server thread/INFO] (Logger) [bclib] Merged 22 additional Surface Rules for 
BCLib - Nether BiomeSource (a855e48)
    biomes     = 36
    namespaces = minecraft(5), betternether(22), cinderscapes(4), regions_unexplored(5)
    seed       = 0
    height     = 256
    config     = BCLibNetherBiomeSourceConfig{mapVersion=hex, useVerticalBiomes=true, amplified=true, biomeSize=256, biomeSizeVertical=80} => 74
[20:52:27] [Server thread/INFO] (Logger) [bclib] Merged 19 additional Surface Rules for 
BCLib - The End  BiomeSource (36b0fe6b)
    biomes     = 39
    namespaces = betterend(19), far_end(8), stellarity(7), minecraft(5)
    seed       = 0
    height     = 256
    deciders   = 1
    config     = BCLEndBiomeSourceConfig{mapVersion=hex, generatorVersion=paulevs, withVoidBiomes=true, innerVoidRadiusSquared=1048576, voidBiomesSize=256, centerBiomesSize=256, landBiomesSize=256, barrensBiomesSize=256} => 30
[20:52:28] [Server thread/ERROR] (Minecraft) Encountered an unexpected exception
java.lang.StackOverflowError: null
	at net.minecraft.class_6916$class_7076.method_41197(class_6916.java:1221) ~[client-intermediary.jar:?]
	at net.minecraft.class_6492$class_6738.method_41187(class_6492.java:214) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7076.method_40469(class_6916.java:1221) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7051.method_40469(class_6916.java:397) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7052.method_40469(class_6916.java:428) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7051.method_40469(class_6916.java:397) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7052.method_40469(class_6916.java:428) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7076$class_7135.method_41530(class_6916.java:1270) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7076.method_41197(class_6916.java:1221) ~[client-intermediary.jar:?]
	at net.minecraft.class_6492$class_6738.method_41187(class_6492.java:214) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7076.method_40469(class_6916.java:1221) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7051.method_40469(class_6916.java:397) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_6917.method_40469(class_6916.java:1179) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7051.method_40469(class_6916.java:397) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_6917.method_40469(class_6916.java:1179) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7051.method_40469(class_6916.java:397) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_6917.method_40469(class_6916.java:1179) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7051.method_40469(class_6916.java:397) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7052.method_40469(class_6916.java:428) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7051.method_40469(class_6916.java:397) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7052.method_40469(class_6916.java:428) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7051.method_40469(class_6916.java:397) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_6917.method_40469(class_6916.java:1179) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7051.method_40469(class_6916.java:397) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_6933.method_40469(class_6916.java:741) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7051.method_40469(class_6916.java:397) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_6933.method_40469(class_6916.java:741) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7051.method_40469(class_6916.java:397) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7052.method_40469(class_6916.java:428) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7076$class_7135.method_41530(class_6916.java:1270) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7076.method_41197(class_6916.java:1221) ~[client-intermediary.jar:?]
	at net.minecraft.class_6492$class_6738.method_41187(class_6492.java:214) ~[client-intermediary.jar:?]
	at net.minecraft.class_6492$class_6738.method_41188(class_6492.java:216) ~[client-intermediary.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at net.minecraft.class_6492$class_6738.method_41187(class_6492.java:216) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7076.method_40469(class_6916.java:1221) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7051.method_40469(class_6916.java:397) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7052.method_40469(class_6916.java:428) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7051.method_40469(class_6916.java:397) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7052.method_40469(class_6916.java:428) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7076$class_7135.method_41530(class_6916.java:1270) ~[client-intermediary.jar:?]
	at net.minecraft.class_6916$class_7076.method_41197(class_6916.java:1221) ~[client-intermediary.jar:?]
	at net.minecraft.class_6492$class_6738.method_41187(class_6492.java:214) ~[client-intermediary.jar:?]
	at net.minecraft.class_6492$class_6738.method_41188(class_6492.java:216) ~[client-intermediary.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at net.minecraft.class_6492$class_6738.method_41187(class_6492.java:216) ~[client-intermediary.jar:?]
	at net.minecraft.class_6492$class_6738.method_41188(class_6492.java:216) ~[client-intermediary.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]... (stacktrace loops)
```

### Other Mods

```shell
Mods:
  [✔] 3dskinlayers-fabric-1.5.3-mc1.20
  [✔] AdditionalStructures-1.20.x-(v.4.2.0)
  [✔] Adorn-5.0.0+1.20.1-fabric
  [✘] advancementinfo-1.20-fabric0.83.0-1.3.1.jar (disabled)
  [✔] advancementscreenshot-1.20.1-4.2
  [✔] alternate-current-mc1.20-1.7.0
  [✘] animatica-0.6+1.20.jar (disabled)
  [✔] anvilrestoration-1.20.1-2.0
  [✔] appleskin-fabric-mc1.20-2.5.0
  [✔] architectury-9.0.8-fabric
  [✔] armor-stand-editor-2.1.1+1.20-rc1
  [✔] authme-7.0.1+1.20
  [✔] autohud-6.1+1.20-fabric
  [✔] AxesAreWeapons-1.6.5-fabric-1.19.3
  [✔] badpackets-fabric-0.4.1
  [✔] balm-fabric-1.20-7.0.4
  [✔] bclib-3.0.10
  [✔] bedrockify-1.9+mc1.20
  [✔] bedrockwaters-1.7.7+1.20.1
  [✔] better_log4j_config-1.1.0-fabric
  [✔] better-clouds-1.2.2-BETA+1.20.1.12a1b70
  [✔] better-end-4.0.7
  [✔] better-nether-9.0.7
  [✔] better-trim-tooltips-1.0.1
  [✔] BetterAdvancements-Fabric-1.20.1-0.3.2.160
  [✔] betterbeaconplacement-1.20.1-3.1
  [✔] betterbeds-1.3.0-1.19.3
  [✔] betterconduitplacement-1.20.1-3.0
  [✔] BetterF3-7.0.0-Fabric-1.20-pre6
  [✔] bettermounthud-1.2.2
  [✔] BetterPingDisplay-Fabric-1.20.1-1.1.1
  [✔] bettersafebed-fabric-1.20-8
  [✔] betterspawnercontrol-1.20.1-4.2
  [✔] betterstats-2.10.3+1.20.1
  [✔] biomemakeover-FABRIC-1.20.0-1.10.1
  [✔] blockus-2.7.2+1.20.1
  [✔] blur-3.1.0
  [✔] Boat-Item-View-Fabric-1.20.1-0.0.5
  [✔] bottledair-1.20.1-2.1
  [✔] brewery-0.4.1+1.20
  [✔] capes-1.5.2+1.20-fabric
  [✘] carpet-fixes-1.20-1.15.2.jar (disabled)
  [✘] caxton-0.4.7+1.20.1.jar (disabled)
  [✔] chat_heads-0.10.16-fabric-1.20
  [✔] cinderscapes-4.0.6
  [✔] CITResewn-1.1.3+1.20
  [✔] cloth-config-11.0.99-fabric
  [✔] clutter-1.20.1-0.3.8
  [✔] collective-1.20.1-6.62
  [✔] colorfulhearts-fabric-1.20-4.0.0
  [✔] comforts-fabric-6.3.3+1.20.1
  [✔] continuity-3.0.0-beta.2+1.20
  [✔] cooldown-coordinator-0.6.2
  [✔] copper-horns-1.0.2
  [✔] cryingportals-1.20.1-2.3
  [✔] ctov-3.3.1
  [✔] cyclepaintings-1.20.1-3.2
  [✔] DamageVignette-2.0.2-fabric+mc1.20.x
  [✔] dark-graph-1.1.0
  [✘] dashloader-5.0.0-beta.1+1.20.0.jar (disabled)
  [✔] day-dream-1.0.8
  [✔] Debugify-1.20.1+1.1
  [✔] deeper-oceans-mc1.20-v1.0.1a
  [✔] defaultoptions-fabric-1.20-18.0.0
  [✔] DetailArmorBar-2.6.3+1.20.1-fabric
  [✔] diamondeconomy-1.5.6
  [✔] diggusmaximus-1.5.9-1.20
  [✔] do-a-barrel-roll-3.0.1+1.20-fabric
  [✔] doubledoors-1.20.1-5.0
  [✔] ductwork-0.7.4
  [✔] dynamic-fps-2.4.0
  [✔] dynamiccrosshair-7.0.2+1.20-fabric
  [✔] eating-animation-1.9.4+1.20
  [✘] ecotones-0.9.2.jar (disabled)
  [✔] elytratrims-1.1.9+1.20
  [✔] emotecraft-for-MC1.20.1-2.2.7-a.build.49-fabric
  [✔] enchant-the-rainbow-1.3.0+1.20.1
  [✔] entity_model_features_fabric_1.20-0.2.11
  [✔] entity_texture_features_fabric_1.20-4.4.4
  [✔] entityculling-fabric-1.6.2-mc1.20
  [✔] fabric-api-0.84.0+1.20.1
  [✔] fabric-carpet-1.20-1.4.112+v230608
  [✔] fabric-language-kotlin-1.9.6+kotlin.1.8.22
  [✔] fabric-seasons-2.2.1+1.20
  [✔] fabric-seasons-extras-1.2-BETA+1.20
  [✔] fabric-seasons-terraformers-compat-1.0
  [✔] fabricskyboxes-0.7.1+mc1.20
  [✔] fallingleaves-1.15.1+1.20.1
  [✔] FallingTree-1.20.1-4.1.1
  [✔] Fastload+1.18.2-1.20-3.4.0
  [✔] featuredservers-1.20-1.7
  [✔] ferritecore-6.0.0-fabric
  [✔] fishontheline-1.20.1-3.0
  [✔] ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
  [✔] friendsandfoes-beekeeperhut-fabric-mc1.20-1.3.0
  [✔] friendsandfoes-fabric-mc1.20.1-1.9.1
  [✔] friendsandfoes-flowerymooblooms-fabric-mc1.20-1.1.0
  [✔] fsb-interop-1.3.2+mc1.20-build.36
  [✔] fusion-1.0.0-fabric-mc1.20
  [✔] geckolib-fabric-1.20-4.2
  [✔] geophilic-v2.0.0-mc1.20u1.20.1
  [✔] global_packs-fabric-1.19.4-1.16.1_fabric
  [✔] graves-3.0.0-beta.4+1.20.1
  [✔] grindstonesharpertools-1.20.1-3.1
  [✔] holdthatchunk-2.0.1+1.19
  [✔] ImmediatelyFast-1.1.15+1.20.1
  [✔] indium-1.0.18+mc1.20
  [✔] interactic-0.2.0+1.20
  [✔] InvMove-1.20-0.8.4-Fabric
  [✔] iris-mc1.20-1.6.4
  [✔] IronChests-2.0.0
  [✔] itemcollectors-1.1.7a-fabric-mc1.20
  [✔] itemswapper-fabric-0.4.0-mc1.20
  [✔] Jade-1.20-fabric-11.1.4
  [✔] jamlib-0.6.0+1.20
  [✔] jeed-1.20-2.1.5-fabric
  [✘] jei-1.20.1-fabric-15.1.0.19.jar (disabled)
  [✔] journeymap-1.20.1-5.9.10-fabric
  [✘] JustEnoughProfessions-fabric-1.20.1-3.0.1.jar (disabled)
  [✘] KeepSomeInventory-MOD-v1.3.0.jar (disabled)
  [✔] kleeslabs-fabric-1.20-15.0.0
  [✔] krypton-0.2.3
  [✘] Ksyxis-1.1.jar (disabled)
  [✔] lambdynamiclights-2.3.1+1.20.1
  [✔] language-reload-1.5.8+1.20.1
  [✔] lazy-language-loader-0.3.3
  [✔] lithium-fabric-mc1.20.1-0.11.2
  [✔] logcleaner-1.0.0
  [✔] lootbeams-2.0.5
  [✔] lunade-fastanim-1.6-1.20
  [✔] LunaSlimes-1.6.1-1.20
  [✔] make_bubbles_pop-0.1.1
  [✔] memoryleakfix-fabric-1.17+-1.1.1
  [✔] memoryusagescreen-fabric-mc1.20-1.9.0
  [✔] midnightlib-fabric-1.4.1.1
  [✔] mineralchance-1.20.1-3.2
  [✔] mixintrace-1.1.1+1.17
  [✔] mob-captains-v2.1.2
  [✔] modelfix-1.14-fabric
  [✔] modernfix-fabric-5.1.1+mc1.20.1
  [✔] modmenu-7.1.0
  [✔] moonlight-1.20-2.5.14-fabric
  [✔] morechathistory-1.19.1-1.1.1
  [✔] moreculling-1.20-0.18.1
  [✔] NBTac-FABRIC-1.20.1-1.1.2
  [✔] NE-1.20.1-1.8.2
  [✔] neruina-1.0.0-fabric+1.20.1
  [✔] netherportalspread-1.20.1-7.5
  [✔] no-telemetry-1.7.0
  [✔] NoChatReports-FABRIC-1.20.1-v2.2.2
  [✔] notenoughanimations-fabric-1.6.4-mc1.20
  [✔] ok-boomer-0.1.2+1.20
  [✔] omnihopper-2.0.3+1.20
  [✔] onsoulfire-1.20.1
  [✔] optigui-2.1.2
  [✔] owo-lib-0.11.0+1.20
  [✔] particle-rain-2.0.6
  [✔] PetOwner-1.8.5-1.19.4+
  [✘] physics-mod-3.0.5-mc-1.20-fabric.jar (disabled)
  [✔] Ping-Wheel-1.3.0-fabric-1.20.1
  [✔] polymer-bundled-0.5.3+1.20.1
  [✘] porting_lib-2.1.1024+1.20-entity-refactor.jar (disabled)
  [✔] PresenceFootsteps-1.9.0
  [✔] profundis-1.5.2
  [✔] puzzle-1.5.1+1.20
  [✔] quartz-elevator-2.2.5+1.20
  [✘] raised-fabric-23w16a-1.2.2.jar (disabled)
  [✔] raknetify-fabric-0.1.0+alpha.5.88-all
  [✔] randommobsizes-fabric-1.20.1-1.3
  [✔] randomshulkercolours-1.20.1-3.0
  [✔] rare-ice-0.6.0
  [✔] rechiseled-1.1.0a-fabric-mc1.20
  [✔] RegionsUnexploredFabric-0.4.1+1.20.1
  [✘] reimaginedmenus-1.0.3-1.20.x.jar (disabled)
  [✔] revamped-trims-1.0.1
  [✔] right-click-harvest-3.2.2+1.19.x-1.20.1-fabric
  [✔] RoughlyEnoughItems-12.0.625
  [✔] RoughlyEnoughProfessions-fabric-1.20.1-2.0.1
  [✔] Rrls-1.20.1-3.1.0-fabric
  [✔] rsls-1.0.1
  [✔] ruined-equipment-2.3.1+1.20.1
  [✔] sbet-v1.0.1
  [✔] scaffoldingdropsnearby-1.20.1-3.0
  [✔] screenfx-1.3.1+1.20.1
  [✔] server-hats-0.16
  [✔] servercore-fabric-1.3.7+1.20.1
  [✘] sfcr-1.7.3-1.20.jar (disabled)
  [✘] Shimmer-fabric-1.20-0.1.15.jar (disabled)
  [✔] simplystatus-1.7.2
  [✔] sleepwarp-2.1.0+1.20
  [✔] slumber-1.1.0
  [✔] sodium-extra-0.4.20+mc1.20-build.103
  [✔] sodium-fabric-mc1.20-0.4.10+build.27
  [✔] sodium-shadowy-path-blocks-3.1.0
  [✔] soundphysics-fabric-1.20.1-1.1.1
  [✔] spark-1.10.42-fabric
  [✘] StackDeobfuscator-1.3.2+fabric.4bca927.jar (disabled)
  [✔] starlight-1.1.2+fabric.dbc156f
  [✔] status-effect-bars-1.0.3
  [✔] stonecutter-damage-1.19.4-mcmeta-13
  [✔] styled-chat-2.2.0+1.20
  [✔] styledplayerlist-3.1.1+1.20.1
  [✔] supermartijn642configlib-1.1.6-fabric-mc1.20
  [✔] supermartijn642corelib-1.1.9-fabric-mc1.20
  [✔] supplementaries-1.20-2.5.15-fabric
  [✔] swordblocking-1.3.1-1.20
  [✔] symbol-chat-1.20.1-1.1.0
  [✔] tectonic-mod-mc1.20-v2
  [✔] TerraBlender-fabric-1.20.1-3.0.0.165
  [✘] Terralith_1.20.x_v2.4.1.jar (disabled)
  [✔] terrestria-6.0.7
  [✔] toms_storage_fabric-1.20-1.6.2
  [✔] tooltipfix-1.1.1-1.20
  [✔] transmog-fabric-1.2.3+1.20
  [✔] travelers-backpack-1.20.1-9.1.1
  [✔] traverse-7.0.7
  [✔] trimmable-tools-mc1.20-v1.0.4
  [✔] trinkets-3.7.0
  [✔] universal_shops-1.3.2+1.20.1
  [✔] vanilla-permissions-0.2.0+1.20
  [✘] vanilla-refresh-1.4.16b.jar (disabled)
  [✔] vcinteraction-1.20.1-1.0.3
  [✔] villagernames-1.20-4.5.1
  [✔] visuality-0.7.0+1.20
  [✔] visualoverhaul-fabric-5.0.1
  [✔] vmp-fabric-mc1.20.1-0.2.0+beta.7.96-all
  [✔] voicechat-fabric-1.20.1-2.4.12
  [✔] waveycapes-fabric-1.4.0-mc1.20
  [✔] waystones-fabric-1.20-14.0.0
  [✔] yet-another-config-lib-fabric-3.0.2+1.20
```

**Comment by CamperSamu** [comment]
I had to disable stack obufscator for this issue too as it ruined the stacktrace and made the wrong crash reason pop

**Comment by quiqueck** [comment]
Thanks for the report. I'll look into it.

**Comment by quiqueck** [comment]
Ok, I tested this, an I can not reproduce the issue. I was testing with Terralith only, Terralith + TerraBlender + RegionsUnexplored and also Terralith + TerraBlender + RegionsUnexplored + Biolith + Cinderscapes + Terrestria + Traverse.

Unfortunately, non of those combinations did cause a crash. Does this happen all of the time for you?

**Comment by CamperSamu** [comment]
It used to happen all of the time, I think some update fixed it?
Sorry but I got busy and I kinda forgot about this :sweat_smile:

I'll close the issue since I have no way of replicating it anymore, thanks anyways!
