### ISSUE TITLE
BCLRecipeBuilder Not creating anvil recipes.

### ISSUE THREAD

**Issue by KodoDenka** [quiqueck/BCLib#118]
### What happened?

On the 1.19.2 version BCLRecipeBuilder.anvil() worked correctly for creating anvil recipes but no longer functions the same on the 1.20 version.

Code blob in question, GitHub - https://github.com/KodoDenka/knavesneeds/blob/1.20.1/common/src/main/java/net/knavesneeds/compat/data/BetterEndRecipesGenerator.java

Log was submitted by a user of my Mod.

### BCLib

3.0.11

### Fabric API

0.85.0+1.20.1

### Fabric Loader

0.14

### Minecraft

1.20.1

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-07-11 10:16:48
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'knavesneeds'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:55)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class org.betterx.betterend.registry.EndBlocks
		at org.betterx.betterend.registry.EndBlockEntities.<clinit>(EndBlockEntities.java:17)
		at org.betterx.betterend.BetterEnd.onInitialize(BetterEnd.java:46)
		at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:55)
		at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36)
		at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62)
		... 15 more
Caused by: java.lang.ExceptionInInitializerError
	at org.betterx.betterend.blocks.basis.PedestalBlock.<clinit>(PedestalBlock.java:63)
	at org.betterx.betterend.complexmaterials.StoneMaterial.<init>(StoneMaterial.java:67)
	at org.betterx.betterend.registry.EndBlocks.<clinit>(EndBlocks.java:175)
	at net.knavesneeds.compat.data.BetterEndRecipesGenerator.register(BetterEndRecipesGenerator.java:140)
	at net.knavesneeds.fabric.KnavesFabric.onInitialize(KnavesFabric.java:15)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:55)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62)
	... 15 more
Caused by: java.lang.NullPointerException: Cannot read the array length because "org.betterx.betterend.registry.EndPortals.portals" is null
	at org.betterx.betterend.registry.EndPortals.getCount(EndPortals.java:50)
	at org.betterx.betterend.blocks.EndBlockProperties.<clinit>(EndBlockProperties.java:16)
	... 23 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:55)
	at net.minecraft.class_310.<init>(class_310.java:458)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.19041.867 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.19041.2913 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.2673 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.19041.2788 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.19041.2788 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.23050.5 (b79513656627928b5505482e6c59e640a77adba5):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:10.0.19041.3031 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.19041.610 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.19041.985 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.19041.2788 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.19041.964 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.28.29913.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.19041.2075 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.19041.1081 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Wldp.dll:Windows Lockdown Policy:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.19041.2075 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.2486 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.2788 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.19041.2913 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.19041.2913 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		javaw.exe:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		jemalloc.dll
		jimage.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		jli.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		jna16635206297808019744.dll:JNA native library:6.1.4:Java(TM) Native Access (JNA)
		jvm.dll:Java HotSpot(TM) 64-Bit server VM:17.0.1.0:Oracle Corporation
		kernel.appcore.dll:AppModel API Host:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		management_ext.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		msvcp140.dll:Microsoft® C Runtime Library:14.28.29913.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		nio.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		ntdll.dll:NT Layer DLL:10.0.19041.2788 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.19041.844 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		svml.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.28.29913.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		win32u.dll:Win32u:10.0.19041.3086 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 432781056 bytes (412 MiB) / 1048576000 bytes (1000 MiB) up to 5309988864 bytes (5064 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx  
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 2.60
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: AMD Radeon(TM) Vega 3 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: DriverVersion=30.0.13025.5005
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 24462.68
	Virtual memory used (MB): 14035.07
	Swap memory total (MB): 18404.38
	Swap memory used (MB): 2592.54
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx5062m
	Fabric Mods: 
		ambientsounds: AmbientSounds 5.2.20
		architectury: Architectury 9.1.10
		argonauts: Argonauts 0.0.0
		bclib: BCLib 3.0.11
			wunderlib: WunderLib 1.1.5
		bettercombat: Better Combat 1.7.2+1.20.1
		betterend: Better End 4.0.8
		betternether: Better Nether 9.0.8
		cadmus: Cadmus 0.0.2
			common-protection-api: Common Protection API 1.0.0
		continents: Continents 1.1.2
		controlling: Controlling For Fabric 12.0.1
		creativecore: CreativeCore 2.10.24
			net_minecraftforge_eventbus: eventbus 6.0.3
		dummmmmmy: MmmMmmMmmMmm 1.20-1.7.9
		emi: EMI 1.0.8+1.20.1+fabric
		entity_model_features: Entity Model Features 0.2.12
		entity_texture_features: Entity Texture Features 4.4.4
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		fabric-api: Fabric API 0.85.0+1.20.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.0+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.8+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.12+b3afc78b77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.8+40e50c4677
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.38+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.42+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.48+b3afc78b77
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.0+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.0+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.0+c154966e77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.0+c154966e77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b377
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.8+e3d6ed2577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.3+43a3fedd77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.0+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		farmersdelight: Farmer's Delight 1.20.1-1.4.0
		ferritecore: FerriteCore 6.0.0
		forgeconfigapiport: Forge Config API Port 8.0.0
		horsebuff: HorseBuff 2.1.1
			cloth-config: Cloth Config v11 11.0.99
				cloth-basic-math: cloth-basic-math 0.6.1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b27
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b27
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b27
		horseinboat: HorseInBoat 1.1.4
		indium: Indium 1.0.21+mc1.20.1
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jade: Jade 11.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		jeed: Just Enough Effects Descriptions 1.20-2.1.5
		jei: Just Enough Items 15.2.0.22
		journeymap: Journeymap 5.9.11
			journeymap-api-fabric: JourneyMap API 1.20-1.9-fabric-SNAPSHOT
		knavesneeds: Knaves' Needs 1.1.4HOTFIX+1.20.1
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lithium: Lithium 0.11.2
		mapfrontiers: MapFrontiers 2.6.0
			commonnetworking: Common Network 1.0.1-1.20.1
		minecraft: Minecraft 1.20.1
		moonlight: Moonlight 1.20-2.6.1
		notenoughanimations: NotEnoughAnimations 1.6.4
		overflowingbars: Overflowing Bars 8.0.0
		player-animator: Player Animator 1.0.2-rc1+1.20
		presencefootsteps: Presence Footsteps 1.9.0
			kirin: Kirin UI 1.15.0
		prometheus: Prometheus 0.0.0
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
		puzzleslib: Puzzles Lib 8.0.7
		quilt_loader: Quilt Loader 0.19.2
		resourcefullib: Resourceful Lib 2.1.1
			com_teamresourceful_yabn: yabn 1.0.3
		searchables: Searchables 1.0.1
		server_translations_api: Server Translations API 2.0.0-beta.2+1.19.4-pre2
			packet_tweaker: Packet Tweaker 0.3.1+23w06a
		simplyswords: Simply Swords 1.48.0-1.21
		sodium: Sodium 0.4.10+build.27
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a27
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b27
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b27
		starlight: Starlight 1.1.2+fabric.dbc156f
		supplementaries: Supplementaries 1.20-2.5.18
		terrablender: TerraBlender 3.0.0.167
			com_electronwill_night-config_core: core 3.6.4
			com_electronwill_night-config_toml: toml 3.6.4
		terralith: Terralith 2.4.2
		trinkets: Trinkets 3.7.0
			cardinal-components-base: Cardinal Components API (base) 5.2.0
			cardinal-components-entity: Cardinal Components API (entities) 5.2.0
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'quilt'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

**Comment by quiqueck** [comment]
In 1.20 you currently need to create recipes in a DataGenerator (https://fabricmc.net/wiki/tutorial:datagen_setup). 

BetterNether does it with this class:
https://github.com/quiqueck/BetterNether/blob/1.20/src/main/java/org/betterx/datagen/betternether/recipes/NetherRecipeDataProvider.java

https://github.com/quiqueck/BetterNether/blob/2a128cd6d4ccee34ea9c3bb3a39cd1fdcae4265c/src/main/java/org/betterx/datagen/betternether/BetterNetherDatagen.java#L25
