### ISSUE TITLE
[Bug] Client method called in server environment, cause a NoClassDefFoundError.

### ISSUE THREAD

**Issue by Harveykang** [quiqueck/BCLib#127]
### What happened?

https://github.com/quiqueck/BCLib/blob/81a5d630c48c13c7cabb751fb2c68ad0b195d8d5/src/main/java/org/betterx/bclib/recipes/AnvilRecipe.java#L147

Reproduced when using anvils of Better End mod in server.

### BCLib

3.0.13

### Minecraft

1.20.1

### Relevant log output

```shell
java.lang.NoClassDefFoundError: net/minecraft/class_310
	at org.betterx.bclib.recipes.AnvilRecipe.craft(AnvilRecipe.java:147)
	at net.minecraft.class_1706.handler$zeb000$bclib$bcl_onTakeAnvilOutput(class_1706.java:1098)
	at net.minecraft.class_1706.method_24923(class_1706.java)
	at net.minecraft.class_4861$2.method_7667(class_4861.java:72)
	at net.minecraft.class_1703.method_34249(class_1703.java:421)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_1703.method_30010(class_1703.java:419)
	at net.minecraft.class_1703.method_7593(class_1703.java:294)
	at net.minecraft.class_3244.method_12076(class_3244.java:1682)
	at net.minecraft.class_2813.method_12191(class_2813.java:58)
	at net.minecraft.class_2813.method_11054(class_2813.java:13)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742)
	at net.minecraft.server.MinecraftServer.handler$zmf000$carpet$modifiedRunLoop(MinecraftServer.java:9451)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_310
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 26 more
```

**Comment by temyy** [comment]
im glad someone else found this error, i reported it 2 weeks ago here #123 but theres no response atleast yet

**Comment by temyy** [comment]
still an issue with bclib-3.0.14

**Comment by liujustin604** [comment]
you can stop it from crashing by replacing `Minecraft.getInstance().level.registryAccess()` with `null` because the `assemble` function doesn't actually use the `RegistryAccess acc` parameter 
its definition is this:
```
@Override
public ItemStack assemble(@NotNull Container craftingInventory, RegistryAccess acc) {
     return this.output.copy();
}
```
