### ISSUE TITLE
[Bug] [1.20.1 Quilt] crashes with c2me, also crashes with vanadium

### ISSUE THREAD

**Issue by glittermutt** [quiqueck/BCLib#134]
### What happened?

two in one haha, the first log is for the c2me crash, the second one is for the vanadium one

### BCLib

latest

### Fabric API

latest

### Fabric Loader

latest

### Minecraft

1.20.1

### Relevant log output

```shell
Description: Feature placement

java.lang.ClassCastException: class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode (java.util.HashMap$Node and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')
	at java.base/java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1986)
	at java.base/java.util.HashMap$TreeNode.treeify(HashMap.java:2102)
	at java.base/java.util.HashMap$TreeNode.split(HashMap.java:2322)
	at java.base/java.util.HashMap.resize(HashMap.java:712)
	at java.base/java.util.HashMap.putVal(HashMap.java:661)
	at java.base/java.util.HashMap.put(HashMap.java:610)
	at org.betterx.betterend.world.structures.piece.MountainPiece.getHeight(MountainPiece.java:115)
	at org.betterx.betterend.world.structures.piece.MountainPiece.getHeightClamp(MountainPiece.java:133)
	at org.betterx.betterend.world.structures.piece.CrystalMountainPiece.method_14931(CrystalMountainPiece.java:93)
	at net.minecraft.class_3449.method_14974(class_3449.java:100)
	at net.minecraft.class_2794.method_38265(class_2794.java:320)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at net.minecraft.class_2794.method_12102(class_2794.java:319)
	at net.minecraft.class_2806.method_51375(class_2806.java:108)
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309)
	at net.minecraft.class_2806.mde81ba7$c2me-threading-worldgen$lambda$runGenerationTask$0$5(class_2806.java:1608)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1163.handler$gme000$betterend$be_getWaterColor(class_1163.java:1041)
	at net.minecraft.class_1163.method_4961(class_1163.java:26)
	at net.minecraft.class_324.method_1694(class_324.java:76)
Mixins in Stacktrace:
	net.minecraft.class_1163:
		vanadium.mixin.biome.BiomeColorsMixin (#vanadium:vanadium.mixins.json)
		org.betterx.betterend.mixin.client.BiomeColorsMixin (#betterend:betterend.mixins.client.json)
		me.flashyreese.mods.sodiumextra.mixin.biome_colors.MixinBiomeColors (#sodium-extra:sodium-extra.mixins.json)
		com.blamejared.ambientenvironment.mixin.BiomeColorsAccessor (#ambientenvironment:ambientenvironment.mixins.json)
	net.minecraft.class_324:
		net.fabricmc.fabric.mixin.client.rendering.BlockColorsMixin (#quilted_fabric_rendering_v1:quilted_fabric_rendering_v1.mixins.json)
		vanadium.mixin.coloring.block.BlockColorsMixin (#vanadium:vanadium.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.model.colors.BlockColorsMixin (#sodium:sodium.mixins.json)
		org.quiltmc.qsl.registry.mixin.client.BlockColorMapMixin (#quilt_registry:quilt_registry.mixins.json)
		vanadium.mixin.coloring.BlockColorsAccessor (#vanadium:vanadium.mixins.json)
		me.tibinonest.mods.cauldron_dyeing.mixin.BlockColorsMixin (#cauldron_dyeing:cauldron-dyeing.mixins.json)

-- Block being rendered --
Details:
	Block: Block{minecraft:water}[level=0]
	Block location: World: (-633,62,1072), Section: (at 7,14,0 in -40,3,67; chunk contains blocks -640,-64,1072 to -625,319,1087), Region: (-2,2; contains chunks -64,64 to -33,95, blocks -1024,-64,1024 to -513,319,1535)
	Chunk section: RenderSection at chunk (-40, 3, 67) from (-640, 48, 1072) to (-625, 63, 1087)
	Render context volume: class_3341{minX=-642, minY=46, minZ=1070, maxX=-623, maxY=65, maxZ=1089}
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:109)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:833)
Mixins in Stacktrace:
	me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask:
		net.coderbot.iris.compat.sodium.mixin.block_id.MixinChunkRenderRebuildTask (#iris:mixins.iris.compat.sodium.json)
		link.infra.indium.mixin.sodium.MixinChunkBuilderMeshingTask (#indium:indium.mixins.json)
		mod.omoflop.mbp.mixin.compat.sodium.ChunkBuilderMeshingTaskMixin (#mbp:mbp.mixins.json)
```

**Comment by quiqueck** [comment]
The next release will have a small change in `BiomeColorsMixin` that might possibly fix the issue.

**Comment by quiqueck** [comment]
Please let me know if the update did not fix the problem for you (just re-open this issue)
