### ISSUE TITLE
[Bug] 1.19 Starting the server causes errors containing "bclib"

### ISSUE THREAD

**Issue by mpustovoi** [quiqueck/BCLib#14]
### What happened?

Hello.
I wanted to play with friends on an Aternos server with mods, most of which are server-side. I installed BetterNether, BetterEnd and Eden Ring mods because they're amazing and I really wanted to play with them. I have the latest version of Fabric API installed as well as BCLib.
In any case, I run into a server crash with an error in the server log containing "bclib". I provided the log and hope I did it right.
The server doesn't yet have a world and no datapacks. Aternos was supposed to create it, I just entered the seed.
Note that I also installed the Terralith mod. Perhaps it somehow conflicts with the worldgen of your mods.
Since I don't understand much about server errors, I would be very grateful if you could help me.
I apologize in advance if this is some stupid mistake of mine.

### BCLib

2.0.8

### Fabric API

0.57.0

### Fabric Loader

0.14.8

### Minecraft

1.19

### Relevant log output

```shell
[18:39:20] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
[18:39:20] [ForkJoinPool-1-worker-1/WARN]: The mod "dungeons_arise" contains invalid entries in its mod json:
- Unsupported root entry "credits" at line 12 column 12
[18:39:21] [main/WARN]: Warnings were found!
 - Mod 'InfiniteVillagerTrading' (infinitevillagertrading) 1.19-fabric0.53.3-1.1 recommends any version of modmenu, which is missing!
	 - You should install any version of modmenu for the optimal experience.
[18:39:21] [main/INFO]: Loading 152 mods:
	- allarrowsinfinityfix 1.3
	- anvilrestoration-fabric 1.3
	- architectury 5.7.28
	- attributefix 15.0.1
	- balm-fabric 4.3.0+0
	- bclib 2.0.8
	- betterbeaconplacement-fabric 1.6
	- betterconduitplacement-fabric 1.5
	- betterend 2.0.2
	- betternether 7.0.2
	- betterspawnercontrol-fabric 1.7
	- betterthanmending 1.3.0
	- bottledair-fabric 1.2
	- bottleyourxp-fabric 1.8
	- breedablekillerrabbit-fabric 1.8
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 7.0.72
	- clumps 9.0.0+3
	- collective-fabric 4.27
	- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
	- compacthelpcommand-fabric 1.3
	- cryingghasts-fabric 1.6
	- cryingportals-fabric 1.3
	- dbm 1.2.0
	- despawningeggshatch-fabric 2.5
	- dismountentity-fabric 1.7
	- doubledoors-fabric 3.4
	- dragondropselytra-fabric 1.6
	- dual_riders 1.1.1
	- dungeons_arise 2.1.51
	- easyelytratakeoff-fabric 2.3
	- edenring 0.6.3
	- editsign 2.4.1
	- enchantingcommands-fabric 2.1
	- endportalrecipe-fabric 2.7
	- erodingstoneentities-fabric 2.6
	- extendedbonemeal-fabric 1.7
	- extractpoison-fabric 1.8
	- fabric 0.57.0+1.19
	- fabric-api-base 0.4.9+e62f51a3a9 via fabric
	- fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.14+b2a4a624a9 via fabric
	- fabric-command-api-v1 1.2.6+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.2+0d55f585a9 via fabric
	- fabric-commands-v0 0.2.23+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.27+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.2.0+07df213ea9 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.1.1+a680b9b4a9 via fabric
	- fabric-dimensions-v1 2.1.28+a6d2f785a9 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.25+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
	- fabric-item-api-v1 1.5.4+767db26ea9 via fabric
	- fabric-item-groups-v0 0.3.25+9ff28f40a9 via fabric
	- fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via fabric
	- fabric-loot-api-v2 1.1.0+03a4e568a9 via fabric
	- fabric-loot-tables-v1 1.1.3+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.10+33fbc738a9 via fabric
	- fabric-networking-api-v1 1.0.27+7fe97409a9 via fabric
	- fabric-networking-v0 0.3.14+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.7+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.8+dc39553aa9 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via invview
	- fabric-registry-sync-v0 0.9.17+23c4cfefa9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.5+a6d2f785a9 via fabric
	- fabric-screen-handler-api-v1 1.2.6+9ff28f40a9 via fabric
	- fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
	- fabricloader 0.14.8
	- fallthroughslime-fabric 1.6
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via collective-fabric
	- firespreadtweaks-fabric 1.4
	- firstjoinmessage-fabric 1.5
	- fishontheline-fabric 1.5
	- fixedanvilrepaircost-fabric 1.8
	- flytre_lib 1.8.8
	- forgottenrecipes 1.19-1.0.0
	- friendsandfoes 1.5.4
	- furnacerecycle-fabric 1.3
	- giantspawn-fabric 2.9
	- grassseeds-fabric 1.8
	- grindenchantments 1.6.4+1.19
	- guardvillagers 1.19-1.0.14
	- handoveryouritems-fabric 1.5
	- healingcampfire-fabric 3.5
	- hoetweaks-fabric 1.5
	- icepreventscropgrowth-fabric 1.6
	- infinitevillagertrading 1.19-fabric0.53.3-1.1
	- inventorytotem-fabric 1.7
	- invview 1.4.9-1.19+
	- java 17
	- justplayerheads-fabric 2.1
	- keepmysoiltilled-fabric 1.2
	- kelpfertilizer-fabric 1.9
	- krypton 0.2.0
	- lazydfu 0.1.3
	- lithium 0.8.0
	- midnightlib 0.5.2
	- milkallthemobs-fabric 1.8
	- minecraft 1.19
	- mineralchance-fabric 1.8
	- mm 2.3 via friendsandfoes
	- mooshroomtweaks-fabric 1.8
	- morevillagers 4.0.2
	- morezombievillagers-fabric 1.7
	- nametagtweaks-fabric 1.9
	- naturallychargedcreepers-fabric 1.9
	- netherportalfix 10.0.0
	- netherportalspread-fabric 5.9
	- noexpensive 1.19-Fabric-1.3.0
	- nohostilesaroundcampfire-fabric 4.0
	- paperbooks-fabric 1.6
	- petnames-fabric 1.8
	- rainbegoneritual-fabric 1.9
	- randombonemealflowers-fabric 1.8
	- randommobeffects-fabric 1.8
	- randomsheepcolours-fabric 1.8
	- recast-fabric 1.7
	- replantingcrops-fabric 2.7
	- repurposed_structures 6.0.8+1.19
	- roughlyenoughitems 9.1.500
	- scaffoldingdropsnearby-fabric 1.7
	- sgui 1.0.0-rc6+1.18-pre5 via invview
	- skeletonhorsespawn-fabric 2.1
	- smallernetherportals-fabric 2.0
	- snowballsfreezemobs-fabric 1.7
	- softerhaybales-fabric 1.7
	- spawnermod 1.1.4
	- stoneholm 1.4.4
	- surfacemushrooms-fabric 1.5
	- terralith 2.3
	- tntbreaksbedrock-fabric 2.0
	- transcendingtrident-fabric 2.3
	- treeharvester-fabric 5.2
	- villagebellrecipe-fabric 1.5
	- villagerdeathmessages-fabric 2.3
	- villagerdrops 1.1.0
	- villagernames-fabric 3.6
	- weakerspiderwebs-fabric 2.2
	- welcomemessage-fabric 1.2
	- wooltweaks-fabric 1.7
	- worldedit 7.2.11-beta-01+6200-0877589
	- zombiehorsespawn-fabric 3.1
	- zombievillagersfromspawner-fabric 1.7
[18:39:22] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/server/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[18:39:22] [main/INFO]: Compatibility level set to JAVA_17
[18:39:23] [main/INFO]: Loaded configuration file for Lithium: 94 options available, 2 override(s) found
[18:39:23] [main/WARN]: Reference map 'morevillagers-fabric-fabric-refmap.json' for morevillagers.mixins.json could not be read. If this is a development environment you can ignore this message
[18:39:25] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[18:39:25] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[18:39:25] [main/WARN]: Error loading class: net/minecraft/class_471 (java.lang.ClassNotFoundException: net/minecraft/class_471)
[18:39:25] [main/WARN]: @Mixin target net.minecraft.class_471 was not found noexpensive.mixins.json:AnvilScreenMixin from mod noexpensive
[18:39:26] [main/WARN]: Error loading class: net/minecraft/class_5513$class_5837 (java.lang.ClassNotFoundException: net/minecraft/class_5513$class_5837)
[18:39:37] [main/INFO]: Building unoptimized datafixer
[18:39:41] [main/INFO]: [bclib] Added Config bclib.main to auto sync (content diff)
[18:39:41] [main/INFO]: [bclib] Added Config bclib.recipes to auto sync (file hash)
[18:39:43] [main/INFO]: [bclib] Added Config betternether.main to auto sync (file hash)
[18:39:43] [main/INFO]: [bclib] Added Config betternether.generator to auto sync (file hash)
[18:39:43] [main/INFO]: [bclib] Added Config betternether.blocks to auto sync (file hash)
[18:39:43] [main/INFO]: [bclib] Added Config betternether.items to auto sync (file hash)
[18:39:43] [main/INFO]: [bclib] Added Config betternether.biomes to auto sync (file hash)
[18:39:43] [main/INFO]: [bclib] Added Config betternether.mobs to auto sync (file hash)
[18:39:43] [main/INFO]: [bclib] Added Config betternether.recipes to auto sync (file hash)
[18:39:43] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchMethodError: 'org.betterx.bclib.api.v2.levelgen.features.BCLFeature org.betterx.bclib.api.v2.levelgen.features.FastFeatures.vine(net.minecraft.class_2960, boolean, boolean, org.betterx.bclib.api.v2.levelgen.features.config.ScatterFeatureConfig$Builder)'
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.NoSuchMethodError: 'org.betterx.bclib.api.v2.levelgen.features.BCLFeature org.betterx.bclib.api.v2.levelgen.features.FastFeatures.vine(net.minecraft.class_2960, boolean, boolean, org.betterx.bclib.api.v2.levelgen.features.config.ScatterFeatureConfig$Builder)'
	at org.betterx.betternether.registry.features.VineLikeFeatures.<clinit>(VineLikeFeatures.java:32) ~[better-nether-7.0.2.jar:?]
	at org.betterx.betternether.registry.NetherBlocks.<clinit>(NetherBlocks.java:741) ~[better-nether-7.0.2.jar:?]
	at org.betterx.betternether.entity.EntityFirefly.<clinit>(EntityFirefly.java:549) ~[better-nether-7.0.2.jar:?]
	at org.betterx.betternether.registry.NetherEntities.<clinit>(NetherEntities.java:152) ~[better-nether-7.0.2.jar:?]
	at net.minecraft.entity.attribute.DefaultAttributeRegistry.handler$zhd000$hasDefinition(DefaultAttributeRegistry.java:1031) ~[server-intermediary.jar:?]
	at net.minecraft.class_5135.method_26875(class_5135.java) ~[server-intermediary.jar:?]
	at net.minecraft.entity.attribute.DefaultAttributeRegistry.method_26876(DefaultAttributeRegistry.java:176) ~[server-intermediary.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.entity.attribute.DefaultAttributeRegistry.checkMissing(DefaultAttributeRegistry.java:178) ~[server-intermediary.jar:?]
	at net.minecraft.Bootstrap.logMissing(Bootstrap.java:136) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:99) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 3 more
```

**Comment by quiqueck** [comment]
Could you please upgrade BetterEnd and BetterNether to the respective latest version and try again.

**Comment by mpustovoi** [comment]
Thank you. I updated everything to the latest version. I think they weren't immediately available on Aternos. I created a single player world with the "BetterX" world type and uploaded it to the server, it started.
Last question. Is the syntax "level-type=betterx" (or something else) correct in server.properties?

**Comment by quiqueck** [comment]
It should be `level-type=bclib\:betterx`
