### ISSUE TITLE
Could not execute entrypoint stage 'client' due to errors, provided by 'bclib'!

### ISSUE THREAD

**Issue by zc1108aaa** [quiqueck/BCLib#174]
### What happened?

error

### BCLib

3.0.14

### Fabric API

0.92.2+1.20.1

### Fabric Loader

0.15.11

### Minecraft

1.20.1

### Relevant log output

```shell
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'bclib'!
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at app//net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at app//net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at MC//net.minecraft.client.MinecraftClient.redirect$bcfb000$notenoughcrashes$catchFabricInit(MinecraftClient.java:14496)
	at MC//net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by zc1108aaa** [comment]
[crash-2024-06-07_16.23.04-client.txt](https://github.com/user-attachments/files/15728098/crash-2024-06-07_16.23.04-client.txt)
