### ISSUE TITLE
[Bug] Incompatibility of BCLib with cardboard mod on server

### ISSUE THREAD

**Issue by LURZU** [quiqueck/BCLib#178]
### What happened?

Hello,
I wanted to install Cardboard on my Fabric server to add plugins (notably FastAsyncWorldEdit), but when I try to start the server with the Cardboard mod, it crashes on startup and gives the logs you can see below, which mention a problem with BCLib mixins.

I hope to find a solution as I cannot find another alternative that is compatible with the FastAsyncWorldEdit plugin.

Thanks in advance !

### BCLib

3.0.14

### Fabric API

0.92.2

### Fabric Loader

0.15.11

### Minecraft

1.20.1

### Relevant log output

```shell
[12:04:56] [main/ERROR]: Mixin apply for mod bclib failed bclib.mixins.common.json:boat.BoatItemMixin from mod bclib -> net.minecraft.class_1749: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_1749::bcl_suse with priority 1000 cannot inject into net/minecraft/class_1749::method_7836(Lnet/minecraft/class_1937;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;)Lnet/minecraft/class_1271; merged by org.cardboardpowered.mixin.item.MixinBoatItem with priority 1000 [PREINJECT Applicator Phase -> bclib.mixins.common.json:boat.BoatItemMixin from mod bclib -> Prepare Injections ->  -> modify$zhi000$bclib$bcl_suse(Lnet/minecraft/class_1297;)Lnet/minecraft/class_1297; -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1749::bcl_suse with priority 1000 cannot inject into net/minecraft/class_1749::method_7836(Lnet/minecraft/class_1937;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;)Lnet/minecraft/class_1271; merged by org.cardboardpowered.mixin.item.MixinBoatItem with priority 1000 [PREINJECT Applicator Phase -> bclib.mixins.common.json:boat.BoatItemMixin from mod bclib -> Prepare Injections ->  -> modify$zhi000$bclib$bcl_suse(Lnet/minecraft/class_1297;)Lnet/minecraft/class_1297; -> Prepare]
        at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:306) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:241) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1028) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970.method_9549(class_4970.java:349) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1293) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843) ~[server-intermediary.jar:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:1185) ~[server-intermediary.jar:?]
        at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.11.jar:?]
[12:04:56] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.11.jar:?]
Caused by: java.lang.ExceptionInInitializerError
        at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
        ... 3 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1749 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1028) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970.method_9549(class_4970.java:349) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1293) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843) ~[server-intermediary.jar:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:1185) ~[server-intermediary.jar:?]
        at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
        ... 3 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1028) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970.method_9549(class_4970.java:349) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1293) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843) ~[server-intermediary.jar:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:1185) ~[server-intermediary.jar:?]
        at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
        ... 3 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [bclib.mixins.common.json:boat.BoatItemMixin from mod bclib] from phase [DEFAULT] in config [bclib.mixins.common.json] FAILED during APPLY
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1028) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970.method_9549(class_4970.java:349) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1293) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843) ~[server-intermediary.jar:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:1185) ~[server-intermediary.jar:?]
        at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
        ... 3 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1749::bcl_suse with priority 1000 cannot inject into net/minecraft/class_1749::method_7836(Lnet/minecraft/class_1937;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;)Lnet/minecraft/class_1271; merged by org.cardboardpowered.mixin.item.MixinBoatItem with priority 1000 [PREINJECT Applicator Phase -> bclib.mixins.common.json:boat.BoatItemMixin from mod bclib -> Prepare Injections ->  -> modify$zhi000$bclib$bcl_suse(Lnet/minecraft/class_1297;)Lnet/minecraft/class_1297; -> Prepare]
        at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:306) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:241) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1028) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970.method_9549(class_4970.java:349) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1293) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843) ~[server-intermediary.jar:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:1185) ~[server-intermediary.jar:?]
        at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
```

### Other Mods

```shell
Cardboard-7 1.20.1
iCommonLibs
Better Ends
```

**Comment by ErzeKawek** [comment]
Cardboard is unstable
