### ISSUE TITLE
Null pointer Exception Crash when starting the game in Forge 1.20.1

### ISSUE THREAD

**Issue by cookienogood** [quiqueck/BCLib#194]
### What happened?

Started the game and it has this brand new error after i added a couple new mods to my modpack. 
![image](https://github.com/user-attachments/assets/6a6bbbf4-9cf4-42a2-a9c3-2a84b7e21a9d)
These are the list of mods I just added. Not sure which one is interfering. 

### BCLib

3.0.14

### WorldWeaver

none

### Minecraft

1.21

### Relevant log output

```shell
org.betterx.bclib.client.models.CustomModelBakery.addItemModel(CustomModelBakery.java:109) ~[bclib-3.0.14_mapped_srg_1.20.1.jar%231672!/:?] {re:classloading,re:mixin}
	at org.betterx.bclib.client.models.CustomModelBakery.lambda$loadCustomModels$1(CustomModelBakery.java:52) ~[bclib-3.0.14_mapped_srg_1.20.1.jar%231672!/:?] {re:classloading,re:mixin}
```

**Comment by LTCatt** [comment]
I can confirm this. It seems to be a random crash.
[crash-2024-10-21_16.41.05-client.txt](https://github.com/user-attachments/files/17458083/crash-2024-10-21_16.41.05-client.txt)

And I found crash reports with the exact same stack on both Minecraft Forums and Reddit:
https://www.minecraftforum.net/forums/support/java-edition-support/3198068-game-crashes
https://www.reddit.com/r/ModdedMinecraft/comments/1elisxg/anyone_have_any_idea_whats_causing_the_crash/
```
java.lang.NullPointerException: Initializing game
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:?] {re:mixin}
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:?] {re:mixin}
	at org.betterx.bclib.client.models.CustomModelBakery.addItemModel(CustomModelBakery.java:109) ~[%5B前置-更好的末地%5D%20bclib-3.0.14_mapped_srg_1.20.1.jar%23997!/:?] {re:classloading,re:mixin}
	at org.betterx.bclib.client.models.CustomModelBakery.lambda$loadCustomModels$1(CustomModelBakery.java:52) ~[%5B前置-更好的末地%5D%20bclib-3.0.14_mapped_srg_1.20.1.jar%23997!/:?] {re:classloading,re:mixin}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[?:?] {}
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at org.betterx.bclib.client.models.CustomModelBakery.loadCustomModels(CustomModelBakery.java:38) ~[bclib-3.0.14_mapped_srg_1.20.1.jar%23997!/:?] {re:classloading,re:mixin}
```

So we've got 4 separate reports, which is enough to prove that this is not an isolated case, but a common one.

Considering it's a ConcurrentHashMap and the crash is random, could this be a problem related to multithreading?

@frankbauer

**Comment by xkotami** [comment]
Same problem here

```
// Hi. I'm Connector, and I'm a crashaholic
=========================
SINYTRA CONNECTOR IS PRESENT!
Please verify issues are not caused by Connector before reporting them to mod authors.
If you're unsure, file a report on Connector's issue tracker found at https://github.com/Sinytra/Connector/issues.
=========================

// Don't be sad, have a hug! <3

Time: 2024-10-22 01:08:03
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:?] {re:mixin}
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:?] {re:mixin}
	at org.betterx.bclib.client.models.CustomModelBakery.addItemModel(CustomModelBakery.java:109) ~[bclib-3.0.14_mapped_srg_1.20.1.jar%231304!/:?] {re:classloading,re:mixin}
	at org.betterx.bclib.client.models.CustomModelBakery.lambda$loadCustomModels$1(CustomModelBakery.java:52) ~[bclib-3.0.14_mapped_srg_1.20.1.jar%231304!/:?] {re:classloading,re:mixin}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[?:?] {}
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) ~[?:?] {}
```

Seems to have something to do with the addItemModel function, hope it gets fixed soon .

**Comment by XXXDark303** [comment]
I think we should fix it ourselves by modifying the source code and making a pull request
