### ISSUE TITLE
 bclib is incompatible with RecipeConfidence.

### ISSUE THREAD

**Issue by Luitito** [quiqueck/BCLib#48]
### What happened?

So, I had a server called ''Jataria 2'' and it was full of structures, farms, chests.. and it was so laggy, so i decided to make a new server, i started it (with fabric version and terralith), then i installed all mods and it crashed, because '' bclib is incompatible with RecipeConfidence.'' I changed the version of bclib to 1.4.6 and it crashed again because betternether 6.1.2 needs bclib 1.4.7, so i installed betternether 6.0.12 and it crashed again because " bclib is incompatible with RecipeConfidence." But in the other serveer bclib runs perfectly! Also, it works with my minecraft, how do i fix it??

### BCLib

1.4.7 / 1.4.6

### Fabric API

0.53.4

### Fabric Loader

0.14.9

### Minecraft

1.18.2

### Relevant log output

```shell
[20:43:28] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.9
[20:43:28] [ForkJoinPool-1-worker-1/WARN]: Mod wmo uses the version fabric1.18.2-v1.5.1 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[20:43:29] [main/INFO]: Loading 119 mods:
	- agape_space 0.5.17
	- alloy_forgery 2.0.13+1.18
	- alloygery 2.0+1.18.2
	- architectury 4.4.65
	- autoconfig1u 3.4.0 via rpgstats
	- backpackmod 1.18.2-3.2.3
	- bclib 1.4.6
	- betterend 1.1.0
	- betternether 6.0.12
	- blue_endless_jankson 1.2.1 via jankson
	- bookshelf 13.2.50
	- botania 1.18.2-433-FABRIC
	- byg 1.4
	- cardinal-components-base 4.1.4 via rpgstats
	- cardinal-components-entity 4.1.4 via rpgstats
	- cloth-api 3.2.64
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-client-events-v0 3.2.64 via cloth-api
	- cloth-common-events-v1 3.2.64 via cloth-api
	- cloth-config 6.2.57
	- cloth-datagen-api-v1 3.2.64 via cloth-api
	- cloth-utils-v1 3.2.64 via cloth-api
	- coinsje 7.0.1
	- com_electronwill_night-config_core 3.6.4 via terrablender
	- com_electronwill_night-config_toml 3.6.4 via terrablender
	- com_typesafe_config 1.4.1 via croptopia
	- croptopia 2.0.3
	- crowdin-translate 1.3+1.17 via the_aether
	- customportalapi 0.0.1-beta49-1.18 via the_aether
	- dehydration 1.2.8
	- edenring 0.5.2
	- ellemes_container_lib 1.4.0-beta.1
	- expandedstorage 7.4.0-beta.2
	- fabric 0.53.4+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.1+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.5+d82b939260 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric
	- fabric-dimensions-v1 2.1.19+ffb2c71e60 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.16+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.5.0+85719ab760 via fabric
	- fabric-item-groups-v0 0.3.12+91896a4960 via fabric
	- fabric-language-kotlin 1.7.4+kotlin.1.6.21
	- fabric-lifecycle-events-v1 2.0.4+d8d7804a60 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.1.1+81ea5b3c60 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.1+032c981d60 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.5.0+2afceb2960 via fabric
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
	- fabric-transfer-api-v1 1.6.2+f4563ac860 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860 via fabric
	- fabricloader 0.14.9
	- fiber 0.23.0-2 via patchouli
	- gobber2 2.5.80
	- gud_recipe_confidence 1.0.2 via the_aether
	- health_levels 1.0.2
	- incubus_core 1.6.6+1.18.1 via the_aether
	- io_leangen_geantyref_geantyref 1.3.11 via croptopia
	- ironfurnaces 3.0.0
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- libgui 5.4.1+1.18.2 via rpgstats
	- libninepatch 1.1.0 via libgui
	- lightstones 1.5.1
	- lithium 0.7.10
	- magna 1.7.0-1.18-pre1 via mythicmetals
	- minecraft 1.18.2
	- more_gems 1.3.71
	- moretags 2.0.2 via the_aether
	- mythicmetals 0.13.1
	- nbtcrafting 2.2.0+mc1.18.2
	- omega-config 1.0.8 via magna
	- org_jetbrains_kotlin_kotlin-reflect 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.2 via fabric-language-kotlin
	- org_spongepowered_configurate-core 4.1.2 via croptopia
	- org_spongepowered_configurate-hocon 4.1.2 via croptopia
	- owo 0.7.2-no-cme+1.18
	- packet_tweaker 0.2.0+1.18-pre1 via server_translations_api
	- patchouli 1.18.2-69-FABRIC
	- plasmo_voice 1.2.19
	- pugh_lib 1.3.2 via gobber2
	- pugh_tools 1.2.7 via gobber2
	- reach-entity-attributes 2.1.1 via botania
	- resourceoverhaul 2.4
	- rpgdifficulty 1.0.12
	- rpgstats 4.3.13+1.18.2
	- seasons 1.4-BETA+1.18
	- seedfix 1.0.1
	- server_translations_api 1.4.12+1.18.2 via rpgstats
	- stacc 1.3.0 via stacker
	- stacker 2.1.3
	- step-height-entity-attribute 1.0.0 via botania
	- team_reborn_energy 2.0.0-beta1 via ironfurnaces
	- terrablender 1.1.0.102
	- the_aether 1.6.9+1.18.1
	- trinkets 3.3.1
	- wmo fabric1.18.2-v1.5.1
[20:43:30] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/server/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[20:43:30] [main/INFO]: Compatibility level set to JAVA_17
[20:43:30] [main/ERROR]: 
[20:43:30] [main/ERROR]: 
[20:43:30] [main/ERROR]: 
[20:43:30] [main/ERROR]: 
[20:43:30] [main/ERROR]: bclib is incompatible with RecipeConfidence.
[20:43:30] [main/ERROR]: 
[20:43:30] [main/ERROR]: There is a chance that the compatibility layer is not correct, issues may arise
[20:43:30] [main/ERROR]: when using recipes (crafting, smelting, etc.) because of the conflict.
[20:43:30] [main/ERROR]: 
[20:43:30] [main/ERROR]: If you are the authors of bclib and have validated the compatibility layer, feel
[20:43:30] [main/ERROR]: free to make a mixin that changes BclibFlag.bclibCompatValidated to return true.
[20:43:30] [main/ERROR]: 
[20:43:30] [main/ERROR]: 
[20:43:30] [main/ERROR]: 
[20:43:30] [main/ERROR]: 
[20:43:31] [main/INFO]: Loaded configuration file for Lithium: 102 options available, 0 override(s) found
[20:43:31] [main/WARN]: Reference map 'plasmovoice-fabric-refmap.json' for plasmovoice.mixins.json could not be read. If this is a development environment you can ignore this message
[20:43:31] [main/WARN]: Error loading class: io/github/apace100/origins/command/OriginCommand (java.lang.ClassNotFoundException: io/github/apace100/origins/command/OriginCommand)
[20:43:31] [main/WARN]: @Mixin target io.github.apace100.origins.command.OriginCommand was not found dehydration.mixins.json:compat.OriginCommandMixin from mod dehydration
[20:43:31] [main/WARN]: Error loading class: io/github/apace100/origins/component/PlayerOriginComponent (java.lang.ClassNotFoundException: io/github/apace100/origins/component/PlayerOriginComponent)
[20:43:31] [main/WARN]: @Mixin target io.github.apace100.origins.component.PlayerOriginComponent was not found dehydration.mixins.json:compat.PlayerOriginComponentMixin from mod dehydration
[20:43:32] [main/WARN]: Error loading class: net/minecraft/class_5602 (java.lang.ClassNotFoundException: net/minecraft/class_5602)
[20:43:32] [main/WARN]: @Mixin target net.minecraft.class_5602 was not found mythicmetals.mixins.json:AccessorEntityModelLayers from mod mythicmetals
[20:43:32] [main/WARN]: Error loading class: net/minecraft/class_1078 (java.lang.ClassNotFoundException: net/minecraft/class_1078)
[20:43:32] [main/WARN]: @Mixin target net.minecraft.class_1078 was not found mythicmetals.mixins.json:TranslationStorageMixin from mod mythicmetals
[20:43:32] [main/WARN]: Error loading class: ru/bclib/api/tag/TagAPI$TagNamed (java.lang.ClassNotFoundException: ru/bclib/api/tag/TagAPI$TagNamed)
[20:43:36] [main/INFO]: alloygery.mixins.json:ItemAccessor from mod alloygery->@Accessor[FIELD_GETTER]::getAttackDamageModifierId()Ljava/util/UUID; should be static as its target is
[20:43:36] [main/INFO]: alloygery.mixins.json:ItemAccessor from mod alloygery->@Accessor[FIELD_GETTER]::getAttackSpeedModifierId()Ljava/util/UUID; should be static as its target is
[20:43:37] [main/ERROR]: Mixin apply for mod betternether failed betternether.mixins.common.json:StructureFeaturesAcessor from mod betternether -> net.minecraft.class_5470: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field field_26306 was not located in the target class net.minecraft.class_5470. Using refmap better-nether-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_26306 was not located in the target class net.minecraft.class_5470. Using refmap better-nether-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) [fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:56) [server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) [server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) [server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
[20:43:37] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5470 failed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5470 failed
	at net.minecraft.class_5458.<clinit>(class_5458.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 3 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5470 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 3 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 3 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [betternether.mixins.common.json:StructureFeaturesAcessor from mod betternether] from phase [DEFAULT] in config [betternether.mixins.common.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 3 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_26306 was not located in the target class net.minecraft.class_5470. Using refmap better-nether-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 3 more
```

### Other Mods

```shell
Agape Space / Space Dimensions Fabric 0.5.17
Alloy Forgery 2.0.13
Alloy Gery 2.0
Architectury 4.4.65
BackpackMod 1.18.2 - 3.2.2
Bclib 1.4.7 / 1.4.6
Better End 1.1.0
Better Nether 6.1.2 (bclib 1.4.7) / 6.0.12 (bclib 1.4.6 / bclib 1.4.7)
Bookshelf 13.2.50
Botania (Fabric/Quilt) 1.18.2-433
Oh The Biomes You'll Go 1.4
Cloth Api 3.2.64
Cloth Config 6.2.57
Croptopia 1.18.2 - 2.0.3
Dehydration 1.2.8
Eden Ring 0.5.2
Ellemes Container Library 1.4.0 - Beta 1
Expanded Storage 7.4.0 - Beta 2
Fabric Api 1.18.2 - 0.53.4
Gobber 2 2.5.80
Health Levels 1.0.2
Iron Furnaces 3.0.0
Lithium 0.7.10
More Gems 1.3.71
Mythic Metals 0.13.1
Nbt Crafting 2.2.0
Owo lib 0.7.2
Patchouli 1.28.2 - 69
Plasmo Voice 1.2.19
Resource Overhaul 2.4
Rpg Difficultu 1.0.12
Rpg Stats 1.18.2 - 4.3.13
Seasons 1.4
Stackeer 2.1.3
Terrablender 1.1.0.102
Paradise Lost 1.18.1 / 1.18.2 - 1.6.9
Trinkets 3.3.1
WayMoreOres 1.18.2 - 1.5.1
(Sorry if i forgot any mod =c)
```

**Comment by quiqueck** [comment]
Unfortunately, there is not much you can do. The Mods are just not working together, and we currently do not add compatibility for the old 1.18 Versions as we had to change the complete code-base for 1.19
