### ISSUE TITLE
[Bug] Issue launching when Optifine is present

### ISSUE THREAD

**Issue by eightmetal** [quiqueck/BCLib#67]
### What happened?

When attempting to load the modpack it failed to load when Optifine was present, when disabled the pack loaded fine.

### BCLib

2.1.5

### Fabric API

0.71.0

### Fabric Loader

0.14.12

### Minecraft

1.19.2

### Relevant log output

```shell
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'bclib'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at org.betterx.betternether.client.BetterNetherClient.registerRenderLayers(BetterNetherClient.java:27)
		at org.betterx.betternether.client.BetterNetherClient.onInitializeClient(BetterNetherClient.java:19)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 8 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at net.fabricmc.fabric.api.renderer.v1.material.BlendMode.<clinit>(BlendMode.java:33)
		at net.fabricmc.fabric.impl.client.indigo.renderer.RenderMaterialImpl.<clinit>(RenderMaterialImpl.java:34)
		at net.fabricmc.fabric.impl.client.indigo.renderer.IndigoRenderer.materialFinder(IndigoRenderer.java:54)
		at net.fabricmc.fabric.impl.client.indigo.renderer.IndigoRenderer.<clinit>(IndigoRenderer.java:37)
		at net.fabricmc.fabric.impl.client.indigo.Indigo.onInitializeClient(Indigo.java:137)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 8 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at at.petrak.hexcasting.client.RegisterClientStuff.init(RegisterClientStuff.java:97)
		at at.petrak.hexcasting.fabric.FabricHexClientInitializer.onInitializeClient(FabricHexClientInitializer.kt:42)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 8 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at io.github.apace100.origins.OriginsClient.onInitializeClient(OriginsClient.java:35)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 8 more
Caused by: java.lang.ExceptionInInitializerError
	at org.betterx.bclib.api.v2.PostInitAPI.processBlockClient(PostInitAPI.java:87)
	at org.betterx.bclib.api.v2.PostInitAPI.lambda$postInit$0(PostInitAPI.java:62)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.betterx.bclib.api.v2.PostInitAPI.postInit(PostInitAPI.java:59)
	at org.betterx.bclib.client.BCLibClient.onInitializeClient(BCLibClient.java:31)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1059 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_4668.<clinit>(class_4668.java:129)
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 19 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_1059::method_18163(Lnet/minecraft/class_3300;Ljava/util/stream/Stream;Lnet/minecraft/class_3695;I)Lnet/minecraft/class_1059$class_4007; has incompatible changes at opcode 159 in callback lootr.mixins.json:MixinTextureAtlas from mod lootr->@Inject::preStitch(Lnet/minecraft/class_3300;Ljava/util/stream/Stream;Lnet/minecraft/class_3695;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/Set;)V.
 Expected: [Ljava/util/Set;]
    Found: [I]
Available: [I, Ljava/util/Set;, Ljava/util/HashSet;, I, Lnet/minecraft/class_1055;, I, I, I]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:547)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1378)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 22 more
```

### Other Mods

```shell
advancementplaques: Advancement Plaques 1.4.6
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.4.62
		bcc: BetterCompatibilityChecker 2.0.2-build.16+mc1.19.1
		bclib: BCLib 2.1.5
		bettercombat: Better Combat 1.5.3+1.19
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.1
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterend: Better End 2.1.2
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		betternether: Better Nether 7.1.2
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.0
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		betterwitchhuts: YUNG's Better Witch Huts 1.19.2-Fabric-2.1.0
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		fabric-api: Fabric API 0.71.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.14+6e0787e690
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.13+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.23+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.4+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.14+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.10+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.31+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.40+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.5+2d2baf4b90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.34+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.3+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.33+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.33+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.3+9785ec3590
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.37+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.3+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.11+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.14+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.6+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.22+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.20+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.10+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.27+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.5+9785ec3590
			fabric-particles-v1: Fabric Particles (v1) 1.0.13+4d0d570390
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.31+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.0+2e5408b590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.0+2e5408b590
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.23+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.18+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.10+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.26+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+08b73de490
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.31+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.6+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.23+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.4+4d0d570390
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.9.0+kotlin.1.8.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.12
		forgeconfigapiport: Forge Config API Port 4.2.9
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		globaldataandresourcepacks: Global Data- & Resourcepacks 1.14.2_fabric
		hexcasting: Hex Casting 0.10.3
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			serialization_hooks: Serialization Hooks 0.3.24
				com_github_llamalad7_mixinextras: MixinExtras 0.0.10
		iceberg: Iceberg 1.0.46
		java: OpenJDK 64-Bit Server VM 17
		legendarytooltips: Legendary Tooltips 1.3.3
		lootr: Lootr 0.4.25.64
		midnightlib: MidnightLib 1.0.0
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.1.2
		nyfsquiver: Nyf's Quivers Fabric-0.5.1-1.19.2
			trinkets: Trinkets 3.5.0
		optifabric: OptiFabric 1.13.16
			mm: Manningham Mills 2.3
		origins: Origins 1.7.1
			apoli: Apoli 2.6.1
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
				playerabilitylib: Pal 1.6.0
		origins-classes: Origins: Classes 1.4.0
		patchouli: Patchouli 1.19.2-77-FABRIC
			fiber: fiber 0.23.0-2
		paucal: PAUCAL 0.5.0
		player-animator: Player Animator 0.4.0
		prism: Prism 1.0.3
		repurposed_structures: Repurposed Structures 6.1.3+1.19.2
		roughlyenoughitems: Roughly Enough Items 9.1.580
			error_notifier: Error Notifier 1.0.9
		roughlyenoughprofessions: Roughly Enough Professions 1.1.3
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		simplyswords: Simply Swords 1.36-1.19.2
		spiderstpo: Spiders 2.0 1.19.2-2.0.3
		terralith: Terralith 2.3
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.2
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
		yungsbridges: YUNG's Bridges 1.19.2-Fabric-3.1.0
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.1.0
```

**Comment by quiqueck** [comment]
I am not really testing with optifine.
