### ISSUE TITLE
[Bug] BCLib 2.2.3 won't let server start.

### ISSUE THREAD

**Issue by nimids** [quiqueck/BCLib#68]
### What happened?

Server instantly crashes.

### BCLib

2.2.3

### Fabric API

0.71.0

### Fabric Loader

0.14.12

### Minecraft

1.19.3

### Relevant log output

```shell
[22:41:42] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.12
[22:41:42] [main/INFO]: Loading 41 mods:
	- bclib 2.2.3
	- fabric-api 0.71.0+1.19.3
	- fabric-api-base 0.4.20+afca2f3e85 via fabric-api
	- fabric-api-lookup-api-v1 1.6.19+49abcf7e85 via fabric-api
	- fabric-biome-api-v1 12.1.0+b5d379b085 via fabric-api
	- fabric-block-api-v1 1.0.4+e022e5d185 via fabric-api
	- fabric-command-api-v1 1.2.20+f71b366f85 via fabric-api
	- fabric-command-api-v2 2.1.16+99f9db8085 via fabric-api
	- fabric-commands-v0 0.2.37+df3654b385 via fabric-api
	- fabric-containers-v0 0.1.46+df3654b385 via fabric-api
	- fabric-content-registries-v0 3.5.0+1d37d50285 via fabric-api
	- fabric-convention-tags-v1 1.2.1+8e4e694f85 via fabric-api
	- fabric-crash-report-info-v1 0.2.13+aeb40ebe85 via fabric-api
	- fabric-data-generation-api-v1 11.1.3+87855a7085 via fabric-api
	- fabric-dimensions-v1 2.1.40+48349a3f85 via fabric-api
	- fabric-entity-events-v1 1.5.6+b83334a085 via fabric-api
	- fabric-events-interaction-v0 0.4.39+3baeb27a85 via fabric-api
	- fabric-events-lifecycle-v0 0.2.41+df3654b385 via fabric-api
	- fabric-game-rule-api-v1 1.0.29+99f9db8085 via fabric-api
	- fabric-item-api-v1 2.1.7+e498f5f085 via fabric-api
	- fabric-item-group-api-v1 2.1.10+0a2a0d0b85 via fabric-api
	- fabric-lifecycle-events-v1 2.2.9+23a79c8a85 via fabric-api
	- fabric-loot-api-v2 1.1.19+75e9821185 via fabric-api
	- fabric-loot-tables-v1 1.1.23+9e7660c685 via fabric-api
	- fabric-message-api-v1 5.0.13+6ede1da985 via fabric-api
	- fabric-mining-level-api-v1 2.1.30+49abcf7e85 via fabric-api
	- fabric-networking-api-v1 1.2.16+4017a8cb85 via fabric-api
	- fabric-networking-v0 0.3.33+df3654b385 via fabric-api
	- fabric-object-builder-api-v1 5.3.0+85f102ee85 via fabric-api
	- fabric-particles-v1 1.0.19+f1e4495b85 via fabric-api
	- fabric-registry-sync-v0 2.0.3+2608564685 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.24+afca2f3e85 via fabric-api
	- fabric-rendering-fluids-v1 3.0.17+f1e4495b85 via fabric-api
	- fabric-resource-conditions-api-v1 2.2.1+280be3ab85 via fabric-api
	- fabric-resource-loader-v0 0.10.4+a91e48b785 via fabric-api
	- fabric-screen-handler-api-v1 1.3.12+99f9db8085 via fabric-api
	- fabric-transfer-api-v1 2.1.13+f1e4495b85 via fabric-api
	- fabric-transitive-access-wideners-v1 2.3.0+5b9a588b85 via fabric-api
	- fabricloader 0.14.12
	- java 17
	- minecraft 1.19.3
[22:41:43] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/P:/AMPDatastore/Instances/TestServer01/Minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[22:41:43] [main/INFO]: Compatibility level set to JAVA_17
[22:41:56] [main/INFO]: Building unoptimized datafixer
[22:42:00] [main/INFO]: [bclib] Added Config bclib.generator to auto sync (file hash)
[22:42:00] [main/INFO]: [bclib] Added Config bclib.main to auto sync (content diff)
[22:42:00] [main/INFO]: [bclib] Added Config bclib.recipes to auto sync (file hash)
[22:42:00] [main/INFO]: [bclib] Added Config bclib.biomes to auto sync (file hash)
[22:42:01] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[22:42:02] [main/INFO]: Found new data pack fabric, loading it automatically
[22:42:04] [main/INFO]: [bclib] Updating Pickers for BCLib - The End  BiomeSource (d4cde5)
[22:42:04] [main/INFO]: [bclib] Unable to build Biome List yet
[22:42:04] [main/INFO]: [bclib] No Void Biomes found. Disabling by using barrens
[22:42:04] [main/INFO]: [bclib] No Barrens Biomes found. Disabling by using land Biomes
[22:42:04] [main/WARN]: [bclib] No Center Island Biomes found. Forcing use of vanilla center.
[22:42:04] [main/INFO]: [bclib] Updating Pickers for BCLib - Nether BiomeSource (57c27be2)
[22:42:04] [main/INFO]: [bclib] Unable to build Biome List yet
[22:42:04] [main/INFO]: [bclib] Updating Pickers for BCLib - The End  BiomeSource (a4529a4)
[22:42:04] [main/INFO]: [bclib] Unable to build Biome List yet
[22:42:04] [main/INFO]: [bclib] No Void Biomes found. Disabling by using barrens
[22:42:04] [main/INFO]: [bclib] No Barrens Biomes found. Disabling by using land Biomes
[22:42:04] [main/WARN]: [bclib] No Center Island Biomes found. Forcing use of vanilla center.
[22:42:04] [main/INFO]: [bclib] Updating Pickers for BCLib - Nether BiomeSource (398611e0)
[22:42:04] [main/INFO]: [bclib] Unable to build Biome List yet
[22:42:04] [main/INFO]: [bclib] Updating Pickers for BCLib - The End  BiomeSource (5c4c89fe)
[22:42:04] [main/INFO]: [bclib] Unable to build Biome List yet
[22:42:04] [main/INFO]: [bclib] No Void Biomes found. Disabling by using barrens
[22:42:04] [main/INFO]: [bclib] No Barrens Biomes found. Disabling by using land Biomes
[22:42:04] [main/WARN]: [bclib] No Center Island Biomes found. Forcing use of vanilla center.
[22:42:04] [main/INFO]: [bclib] Updating Pickers for BCLib - Nether BiomeSource (4a36d9af)
[22:42:04] [main/INFO]: [bclib] Unable to build Biome List yet
[22:42:04] [main/INFO]: [bclib] Updating Pickers for BCLib - The End  BiomeSource (39e9a37b)
[22:42:04] [main/INFO]: [bclib] Unable to build Biome List yet
[22:42:04] [main/INFO]: [bclib] No Void Biomes found. Disabling by using barrens
[22:42:04] [main/INFO]: [bclib] No Barrens Biomes found. Disabling by using land Biomes
[22:42:04] [main/WARN]: [bclib] No Center Island Biomes found. Forcing use of vanilla center.
[22:42:04] [main/INFO]: [bclib] Updating Pickers for BCLib - Nether BiomeSource (742035e6)
[22:42:04] [main/INFO]: [bclib] Unable to build Biome List yet
[22:42:04] [main/WARN]: [bclib] No valid Biome Registry available!
[22:42:04] [main/INFO]: [worlds_together] Creating a new World, no fixes needed
[22:42:04] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5455.method_30530(net.minecraft.class_5321)" because "access" is null
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:199) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric.jar:0.11.1]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5455.method_30530(net.minecraft.class_5321)" because "access" is null
	at org.betterx.worlds.together.worldPreset.WorldPresets.get(WorldPresets.java:35) ~[bclib-2.2.3.jar:?]
	at org.betterx.worlds.together.world.event.WorldBootstrap$Helpers.defaultServerPreset(WorldBootstrap.java:76) ~[bclib-2.2.3.jar:?]
	at org.betterx.worlds.together.world.event.WorldBootstrap$Helpers.defaultServerDimensions(WorldBootstrap.java:83) ~[bclib-2.2.3.jar:?]
	at org.betterx.worlds.together.world.event.WorldBootstrap$DedicatedServer.setupWorld(WorldBootstrap.java:122) ~[bclib-2.2.3.jar:?]
	at net.minecraft.server.Main.modify$zzb000$bcl_onCreate(Main.java:533) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_43613(Main.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:42) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_43612(Main.java:152) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:942) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:936) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:150) ~[server-intermediary.jar:?]
	... 5 more
```

**Comment by tomcrusade** [comment]
Hmm 2.2.4, 2.2.2, 2.2.1 seems to broke as well. Even with these is still not working:
- newest fabric API 0.73.0 and fabric loader 0.14.3
- loader_version=0.14.11, fabric_version=0.68.1+1.19.3, bclib 2.2.4 (according to gradle.properties)

**Comment by AliahX** [comment]
I've got the same error.

**Comment by tomcrusade** [comment]
Okay, some people might have some temporary remedy for this issue in https://github.com/quiqueck/BCLib/issues/72

**Comment by Nitjsefnie** [comment]
Could someone close this as duplicate of https://github.com/quiqueck/BCLib/issues/72 ?
