### ISSUE TITLE
[Bug] Client crashes on connection

### ISSUE THREAD

**Issue by EmetDuncan** [quiqueck/BCLib#69]
### What happened?

Started a LAN server. Host runs perfectly fine but when another client tries to join, they will crash on connect. This only happenes with BCLib even when BetterEnd or BetterNether arent present.

[crash-2023-01-07_20.18.40-client.txt](https://github.com/quiqueck/BCLib/files/10367534/crash-2023-01-07_20.18.40-client.txt)

BetterEnd
3.1.1
BetterNether
8.1.2

### BCLib

2.2.3

### Fabric API

0.72.0

### Fabric Loader

0.14.12

### Minecraft

1.19.3

### Relevant log output

```shell
[20:18:35] [Render thread/INFO]: [bclib] Sending hello to server.
[20:18:36] [Render thread/ERROR]: [worlds_together] Tried to read from global registry!
[20:18:37] [Render thread/ERROR]: Unreported exception thrown! java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5455.method_30530(net.minecraft.class_5321)" because the return value of "org.betterx.worlds.together.world.event.WorldBootstrap.getLastRegistryAccessOrElseBuiltin()" is null at org.betterx.bclib.api.v2.levelgen.biomes.BiomeAPI.getRenderBiome(BiomeAPI.java:443) ~[bclib-2.2.3.jar:?]
	at org.betterx.bclib.client.render.CustomFogRenderer.shouldIgnore(CustomFogRenderer.java:120) ~[bclib-2.2.3.jar:?]	
	at org.betterx.bclib.client.render.CustomFogRenderer.shouldIgnoreArea(CustomFogRenderer.java:110) ~[bclib-2.2.3.jar:?]
	at org.betterx.bclib.client.render.CustomFogRenderer.applyFogDensity(CustomFogRenderer.java:42) ~[bclib-2.2.3.jar:?]	
	at net.minecraft.class_758.handler$zde000$bclib_fogDensity(class_758.java:569) ~[client-intermediary.jar:?]	
	at net.minecraft.class_758.method_3211(class_758.java) ~[client-intermediary.jar:?]	
	at net.minecraft.class_761.method_37365(class_761.java:1234) ~[client-intermediary.jar:?]	
	at net.minecraft.class_761.method_3257(class_761.java:2004) ~[client-intermediary.jar:?]	
	at net.minecraft.class_761.method_22710(class_761.java:1234) ~[client-intermediary.jar:?]	
	at net.minecraft.class_757.method_3188(class_757.java:1085) ~[client-intermediary.jar:?]	
	at net.minecraft.class_757.method_3192(class_757.java:864) ~[client-intermediary.jar:?]	
	at net.minecraft.class_310.method_1523(class_310.java:1193) ~[client-intermediary.jar:?]	
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]	
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[minecraft-1.19.3-client.jar:?]	
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]	
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]	
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]	
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]	
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
[20:18:39] [Render thread/INFO]: Minimap session finalized.
[20:18:39] [Render thread/INFO]: Stopping worker threads
```

### Other Mods

```shell
BiomesOPlenty-1.19.3-17.2.0.494
cloth-config-9.0.94-fabric
Companion-1.19.3-fabric-4.0.0
fabric-api-0.72.0+1.19.3
indium-1.0.12+mc1.19.3
iris-mc1.19.3-1.5.1
lithium-fabric-mc1.19.3-0.10.4
midnightlib-fabric-1.1.0
phosphor-fabric-mc1.19.x-0.8.1
repurposed_structures_fabric-6.3.1+1.19.3
sodium-fabric-mc1.19.3-0.4.8+build.22
TerraBlender-fabric-1.19.3-2.1.0.139
Xaeros_Minimap_22.17.0_Fabric_1.19.3
```

**Comment by JosephTheMan** [comment]
I have this exact same problem! For some reason "fob" is messing up the game and I don't know why.
