### ISSUE TITLE
[Bug] Bakery Not loading.

### ISSUE THREAD

**Issue by J9Shee** [quiqueck/BCLib#74]
### What happened?

The game crashed whilst initializing game
Error: java.lang.NullPointerException: Cannot invoke "org.betterx.bclib.client.models.CustomModelBakery.loadCustomModels(net.minecraft.class_3300)" because "org.betterx.bclib.client.BCLibClient.modelBakery" is null
This happens when i launch my game.

1.19.3 Bclib 2.24
Latest version of fabric

### BCLib

2.24

### Fabric API

latest version

### Fabric Loader

latest version

### Minecraft

1.19.3

### Relevant log output

---- Minecraft Crash Report ----
// My bad.

Time: 2023-02-07 05:22:23
Description: Initializing game

java.lang.NullPointerException: Cannot invoke "org.betterx.bclib.client.models.CustomModelBakery.loadCustomModels(net.minecraft.class_3300)" because "org.betterx.bclib.client.BCLibClient.modelBakery" is null
	at net.minecraft.class_1092.handler$zef000$bclib_loadCustomModels(class_1092.java:530)
	at net.minecraft.class_1092.method_25931(class_1092.java:82)
	at net.minecraft.class_4014.method_18368(class_4014.java:32)
	at net.minecraft.class_4014.<init>(class_4014.java:44)
	at net.minecraft.class_4014.method_18369(class_4014.java:32)
	at net.minecraft.class_4014.method_40087(class_4014.java:101)
	at net.minecraft.class_3304.method_18232(class_3304.java:47)
	at net.minecraft.class_310.<init>(class_310.java:652)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by itsdeadfrosty** [comment]
this mods prob dead bro. best to just not use BCLIB
