### ISSUE TITLE
[Bug] [1.19.2] Disabling Blocks in blocks.json leads to crash on game load

### ISSUE THREAD

**Issue by grundyboy34** [quiqueck/BCLib#83]
### What happened?

I disabled the nether respawner statue in blocks.json, and then the game crashes on load.

### BCLib

2.1.6

### Fabric API

0.75.1+1.19.2

### Fabric Loader

0.14.17

### Minecraft

1.19.2

### Relevant log output

```shell
[13:10:25] [Render thread/ERROR]: Unhandled game exception
java.lang.IllegalStateException: Some intrusive holders were not added to registry: [Reference{null=Block{minecraft:air}}]
	at net.minecraft.class_2370.method_40276(class_2370.java:352) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_40292(class_2378.java:404) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.handler$bji002$fabric-registry-sync-v0$onStart(class_310.java:8486) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:747) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.17.jar:?]
```

**Comment by Rebel459** [comment]
same issue with Eden Ring and changing Guidebook to false
