### ISSUE TITLE
[Bug] Open server 1.19 error !

### ISSUE THREAD

**Issue by Zeptana** [quiqueck/BCLib#9]
### What happened?

Hey,

I was trying to open a server with Better End mod, but this happened...
Hope u will find a fix ! :)

### BCLib

2.0.5

### Fabric API

0.56.1

### Fabric Loader

0.14.8

### Minecraft

1.19

### Relevant log output

```shell
[02:18:07] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
[02:18:08] [main/INFO]: Loading 42 mods:
	- bclib 2.0.5
	- betterend 2.0.2
	- fabric 0.56.1+1.19
	- fabric-api-base 0.4.9+e62f51a3a9 via fabric
	- fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.14+b2a4a624a9 via fabric
	- fabric-command-api-v1 1.2.6+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.2+0d55f585a9 via fabric
	- fabric-commands-v0 0.2.23+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.27+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.1.1+82552130a9 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.1.0+a680b9b4a9 via fabric
	- fabric-dimensions-v1 2.1.27+72da3b3da9 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.25+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
	- fabric-item-api-v1 1.5.4+767db26ea9 via fabric
	- fabric-item-groups-v0 0.3.24+9ff28f40a9 via fabric
	- fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via fabric
	- fabric-loot-api-v2 1.0.2+9e7660c6a9 via fabric
	- fabric-loot-tables-v1 1.1.2+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.9+33fbc738a9 via fabric
	- fabric-networking-api-v1 1.0.27+7fe97409a9 via fabric
	- fabric-networking-v0 0.3.14+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.6+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.8+dc39553aa9 via fabric
	- fabric-registry-sync-v0 0.9.16+92cf9a3ea9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.4+db8596f1a9 via fabric
	- fabric-screen-handler-api-v1 1.2.6+9ff28f40a9 via fabric
	- fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
	- fabricloader 0.14.8
	- java 17
	- minecraft 1.19
	- roughlyenoughitems 9.0.491
[02:18:08] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/user/Desktop/serv/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[02:18:08] [main/INFO]: Compatibility level set to JAVA_17
[02:18:09] [main/WARN]: Error loading class: net/minecraft/class_5293 (java.lang.ClassNotFoundException: net/minecraft/class_5293)
[02:18:09] [main/WARN]: @Mixin target net.minecraft.class_5293 was not found bclib.mixins.common.json:PresetEditorMixin from mod bclib
[02:18:09] [main/WARN]: Error loading class: net/minecraft/class_7196 (java.lang.ClassNotFoundException: net/minecraft/class_7196)
[02:18:09] [main/WARN]: @Mixin target net.minecraft.class_7196 was not found bclib.mixins.common.json:WorldOpenFlowsMixin from mod bclib
[02:18:18] [main/INFO]: Building unoptimized datafixer
[02:18:21] [main/INFO]: [bclib] Added Config bclib.main to auto sync (content diff)
[02:18:21] [main/INFO]: [bclib] Added Config bclib.recipes to auto sync (file hash)
[02:18:22] [main/INFO]: [bclib] Added Config betterend.entities to auto sync (file hash)
[02:18:22] [main/INFO]: [bclib] Added Config betterend.blocks to auto sync (file hash)
[02:18:22] [main/INFO]: [bclib] Added Config betterend.items to auto sync (file hash)
[02:18:22] [main/INFO]: [bclib] Added Config betterend.biomes to auto sync (file hash)
[02:18:22] [main/INFO]: [bclib] Added Config betterend.recipes to auto sync (file hash)
[02:18:22] [main/INFO]: [bclib] Added Config betterend.enchantments to auto sync (file hash)
[02:18:32] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'roughlyenoughitems'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.8.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.RuntimeException: Architectury API is not installed! https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/all
	at me.shedaniel.rei.RoughlyEnoughItemsState.error(RoughlyEnoughItemsState.java:62) ~[RoughlyEnoughItems-9.0.491.jar:?]
	at me.shedaniel.rei.fabric.RoughlyEnoughItemsInitializerImpl.checkMods(RoughlyEnoughItemsInitializerImpl.java:62) ~[RoughlyEnoughItems-9.0.491.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.checkMods(RoughlyEnoughItemsInitializer.java) ~[RoughlyEnoughItems-9.0.491.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:45) ~[RoughlyEnoughItems-9.0.491.jar:?]
	at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198) ~[?:?]
	at com.sun.proxy.jdk.proxy3.$Proxy32.onInitialize(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]
	... 7 more
```

### Other Mods

```shell
BetterEnd
RoughlyEnoughItems
```

**Comment by quiqueck** [comment]
Thanks for reporting, but I think this is not a Problem with BE. You need to install Architecture for REI to work:

`Architectury API is not installed! https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/all`
